import type { FastifyInstance } from 'fastify';
import type { ServiceRegistry } from '../shared/types/service-registry.js';
import { registerAuthRoutes } from './auth/auth.routes.js';
import { registerHealthRoutes } from './health/health.routes.js';
import { registerPermissionRoutes } from './permissions/permission.routes.js';
import { registerPatientRoutes } from './patients/patient.routes.js';
import { registerRoleRoutes } from './roles/role.routes.js';
import { registerUserRoutes } from './users/user.routes.js';
import { registerBranchRoutes } from './branches/branch.routes.js';
import { registerDepartmentRoutes } from './departments/department.routes.js';
import { registerDoctorRoutes } from './doctors/doctor.routes.js';
import { registerOpdConsultationRoutes } from './opd/opd-consultation.routes.js';
import { registerOpdClinicalOrderRoutes } from './opd/opd-clinical-order.routes.js';
import { registerOpdPrescriptionRoutes } from './opd/opd-prescription.routes.js';
import { registerOpdFollowUpRoutes } from './opd/opd-follow-up.routes.js';
import { registerOpdReferralRoutes } from './opd/opd-referral.routes.js';
import { registerOpdVitalsRoutes } from './opd/opd-vitals.routes.js';
import { registerOpdVisitRoutes } from './opd/opd-visit.routes.js';
import { registerAppointmentRoutes } from './appointments/appointment.routes.js';
import { registerServiceRoutes } from './services/service.routes.js';
import { registerMedicineRoutes } from './medicines/medicine.routes.js';
import { registerPharmacyInventoryRoutes } from './pharmacy-inventory/pharmacy-inventory.routes.js';
import { registerLaboratoryRoutes } from './laboratory/laboratory.routes.js';
import { registerImagingRoutes } from './imaging/imaging.routes.js';
import { registerBillingRoutes } from './billing/billing.routes.js';
import { registerSettingsRoutes } from './settings/settings.routes.js';
import { registerAdministrationDashboardRoutes } from './administration-dashboard/administration-dashboard.routes.js';
import { registerNotificationRoutes } from './notifications/index.js';
import { registerPharmacyDispensingRoutes } from './pharmacy-dispensing/pharmacy-dispensing.routes.js';
import { registerAdmissionsConfigurationRoutes } from './admissions-configuration/admissions-configuration.routes.js';
import { registerInpatientAdmissionRoutes } from './inpatient-admissions/inpatient-admission.routes.js';

export const registerModules = async (app: FastifyInstance, services: ServiceRegistry) => {
  await registerHealthRoutes(app, services);
  await registerAuthRoutes(app, services);
  await registerAdministrationDashboardRoutes(app, services);
  await registerUserRoutes(app, services);
  await registerRoleRoutes(app, services);
  await registerPermissionRoutes(app, services);
  await registerBranchRoutes(app, services);
  await registerDepartmentRoutes(app, services);
  await registerServiceRoutes(app, services);
  await registerMedicineRoutes(app, services);
  await registerPharmacyInventoryRoutes(app, services);
  await registerLaboratoryRoutes(app, services);
  await registerImagingRoutes(app, services);
  await registerBillingRoutes(app, services);
  await registerSettingsRoutes(app, services);
  await registerPatientRoutes(app, services);
  await registerDoctorRoutes(app, services);
  await registerAppointmentRoutes(app, services);
  await registerOpdVisitRoutes(app, services);
  await registerOpdVitalsRoutes(app, services);
  await registerOpdConsultationRoutes(app, services);
  await registerOpdClinicalOrderRoutes(app, services);
  await registerOpdPrescriptionRoutes(app, services);
  await registerOpdFollowUpRoutes(app, services);
  await registerOpdReferralRoutes(app, services);
  await registerNotificationRoutes(app, services);
  await registerPharmacyDispensingRoutes(app, services);
  await registerAdmissionsConfigurationRoutes(app, services);
  await registerInpatientAdmissionRoutes(app, services);
};
