import { zodResolver } from '@hookform/resolvers/zod';
import { useState } from 'react';
import { useForm } from 'react-hook-form';
import { toast } from 'sonner';
import { z } from 'zod';
import type { ApiClinicalOrderType, SaveOpdClinicalOrderPayload, SaveOpdPrescriptionPayload } from '../../api/opd';
import type { ServiceResponse } from '../../api/services';

const prescriptionSchema = z.object({ medicine_name: z.string().trim().min(1), strength: z.string(), dosage: z.string().trim().min(1), route: z.string().trim().min(1), frequency: z.string().trim().min(1), duration: z.string().trim().min(1), quantity: z.coerce.number().int().positive() });
const orderSchema = z.object({ service_id: z.string().min(1, 'Select a service'), priority: z.enum(['ROUTINE', 'URGENT', 'STAT']), specimen_type: z.string(), clinical_notes: z.string() });
type PrescriptionInput = z.input<typeof prescriptionSchema>; type PrescriptionValues = z.output<typeof prescriptionSchema>; type OrderValues = z.infer<typeof orderSchema>; type Mode = 'PRESCRIPTION' | ApiClinicalOrderType | null;
type Props = { active: boolean; canCreatePrescription?: boolean; prescriptionExists: boolean; laboratoryExists: boolean; imagingExists: boolean; laboratoryServices: ServiceResponse[]; imagingServices: ServiceResponse[]; pending: boolean; onPrescription: (payload: SaveOpdPrescriptionPayload) => Promise<unknown>; onOrder: (type: ApiClinicalOrderType, payload: SaveOpdClinicalOrderPayload) => Promise<unknown> };

export function DownstreamOrdersPanel({ active, canCreatePrescription = true, prescriptionExists, laboratoryExists, imagingExists, laboratoryServices, imagingServices, pending, onPrescription, onOrder }: Props) {
  const [mode, setMode] = useState<Mode>(null);
  const prescription = useForm<PrescriptionInput, unknown, PrescriptionValues>({ resolver: zodResolver(prescriptionSchema), defaultValues: { medicine_name: '', strength: '', dosage: '', route: 'Oral', frequency: '', duration: '', quantity: 1 } });
  const order = useForm<OrderValues>({ resolver: zodResolver(orderSchema), defaultValues: { service_id: '', priority: 'ROUTINE', specimen_type: '', clinical_notes: '' } });
  if (!active) return null;
  const submitPrescription = prescription.handleSubmit(async (values) => { try { await onPrescription({ items: [{ ...values, strength: values.strength || null, intake_time: null, instructions: null }], doctor_instructions: null, patient_instructions: null }); toast.success('Prescription submitted to Pharmacy.'); setMode(null); } catch (error) { toast.error(error instanceof Error ? error.message : 'Prescription submission failed.'); } });
  const submitOrder = order.handleSubmit(async (values) => { if (mode !== 'LABORATORY' && mode !== 'IMAGING') return; const services = mode === 'LABORATORY' ? laboratoryServices : imagingServices; const selected = services.find((item) => item.id === values.service_id); if (!selected) return; try { await onOrder(mode, { priority: values.priority, specimen_type: mode === 'LABORATORY' ? values.specimen_type || null : null, destination: null, items: [{ service_id: selected.id, investigation_name: selected.name, category: selected.category ?? selected.service_type }], clinical_notes: values.clinical_notes || null, instructions: null }); toast.success(`${mode === 'LABORATORY' ? 'Laboratory' : 'Imaging'} order submitted.`); setMode(null); } catch (error) { toast.error(error instanceof Error ? error.message : 'Clinical order submission failed.'); } });
  const services = mode === 'LABORATORY' ? laboratoryServices : imagingServices;
  return <section className="prerequisite-panel"><strong>Downstream clinical requests</strong><div className="page-actions">{canCreatePrescription ? <button type="button" className="btn-secondary compact" disabled={prescriptionExists} onClick={() => setMode('PRESCRIPTION')}>{prescriptionExists ? 'Pharmacy sent' : 'Send to Pharmacy'}</button> : null}<button type="button" className="btn-secondary compact" disabled={laboratoryExists} onClick={() => setMode('LABORATORY')}>{laboratoryExists ? 'Laboratory sent' : 'Order Laboratory'}</button><button type="button" className="btn-secondary compact" disabled={imagingExists} onClick={() => setMode('IMAGING')}>{imagingExists ? 'Imaging sent' : 'Order Imaging'}</button></div>{mode === 'PRESCRIPTION' && canCreatePrescription ? <form className="form-grid" onSubmit={submitPrescription}><label className="form-grid__full">Medicine *<input {...prescription.register('medicine_name')} /></label><label>Strength<input {...prescription.register('strength')} /></label><label>Quantity *<input type="number" {...prescription.register('quantity')} /></label><label>Dosage *<input {...prescription.register('dosage')} /></label><label>Route *<input {...prescription.register('route')} /></label><label>Frequency *<input {...prescription.register('frequency')} /></label><label>Duration *<input {...prescription.register('duration')} /></label><div className="form-grid__full page-actions"><button type="button" className="btn-secondary" onClick={() => setMode(null)}>Close</button><button className="btn-primary" disabled={pending}>Submit Prescription</button></div></form> : mode && mode !== 'PRESCRIPTION' ? <form className="form-grid" onSubmit={submitOrder}><label className="form-grid__full">Service *<select {...order.register('service_id')}><option value="">Select service</option>{services.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label>Priority<select {...order.register('priority')}><option value="ROUTINE">Routine</option><option value="URGENT">Urgent</option><option value="STAT">STAT</option></select></label>{mode === 'LABORATORY' ? <label>Specimen *<input {...order.register('specimen_type')} /></label> : null}<label className="form-grid__full">Clinical notes<textarea {...order.register('clinical_notes')} /></label><div className="form-grid__full page-actions"><button type="button" className="btn-secondary" onClick={() => setMode(null)}>Close</button><button className="btn-primary" disabled={pending}>Submit Order</button></div></form> : null}</section>;
}
