import mongoose, { Types, type ClientSession } from 'mongoose';
import { type SequenceService } from '../../shared/sequence/sequence.service.js';
import { BedHoldModel } from '../admissions-configuration/admissions-configuration.model.js';
import { AppointmentModel } from '../appointments/appointment.model.js';
import { AuditLogModel } from '../auth/auth.model.js';
import { BranchModel } from '../branches/branch.model.js';
import { DepartmentModel } from '../departments/department.model.js';
import { DoctorModel } from '../doctors/doctor.model.js';
import { OpdVisitModel } from '../opd/opd-visit.model.js';
import { PatientModel } from '../patients/patient.model.js';
import { RoleModel } from '../roles/role.model.js';
import { ServiceModel } from '../services/service.model.js';
import { UserModel } from '../users/user.model.js';
import { ProcedureBookingModel, ProcedureRecommendationModel, type ProcedureBookingFields, type ProcedureRecommendationFields } from './surgery.model.js';
import type { CreateProcedureBookingDTO, CreateProcedureRecommendationDTO, SurgeryListQuery, SurgeryMetadata } from './surgery.types.js';

const oid = (value: string) => new Types.ObjectId(value);
const paging = (total: number, page: number, limit: number) => ({ total, page, limit, totalPages: Math.ceil(total / limit) || 1 });
export type RecommendationLean = ProcedureRecommendationFields & { _id: Types.ObjectId };
export type BookingLean = ProcedureBookingFields & { _id: Types.ObjectId };
const recommendationDto = (item: RecommendationLean) => ({ id: item._id.toString(), recommendation_number: item.recommendationNumber, patient_id: item.patientId.toString(), patient_number: item.patientNumber, patient_name: item.patientName, branch_id: item.branchId.toString(), department_id: item.departmentId.toString(), department_name: item.departmentName, recommending_doctor_id: item.recommendingDoctorId.toString(), recommending_doctor_name: item.recommendingDoctorName, service_id: item.serviceId.toString(), service_name: item.serviceName, encounter_type: item.encounterType, encounter_id: item.encounterId.toString(), clinical_reason: item.clinicalReason, notes: item.notes ?? null, status: item.status, booking_id: item.bookingId?.toString() ?? null, cancellation_reason: item.cancellationReason ?? null, created_at: item.createdAt, updated_at: item.updatedAt });
const bookingDto = (item: BookingLean) => ({ id: item._id.toString(), booking_number: item.bookingNumber, recommendation_id: item.recommendationId.toString(), patient_id: item.patientId.toString(), patient_number: item.patientNumber, patient_name: item.patientName, branch_id: item.branchId.toString(), department_id: item.departmentId.toString(), department_name: item.departmentName, service_id: item.serviceId.toString(), service_name: item.serviceName, doctor_id: item.doctorId.toString(), doctor_name: item.doctorName, scheduled_start: item.scheduledStart, scheduled_end: item.scheduledEnd, duration_minutes: item.durationMinutes, status: item.status, hold_id: item.holdId?.toString() ?? null, consent_document_id: item.consentDocumentId?.toString() ?? null, deposit_invoice_id: item.depositInvoiceId?.toString() ?? null, prerequisite_snapshot: item.prerequisiteSnapshot ?? null, notes: item.notes ?? null, schedule_history: item.scheduleHistory.map((row) => ({ previous_start: row.previousStart, previous_end: row.previousEnd, new_start: row.newStart, new_end: row.newEnd, previous_doctor_id: row.previousDoctorId.toString(), new_doctor_id: row.newDoctorId.toString(), reason: row.reason, changed_by: row.changedBy.toString(), changed_at: row.changedAt })), cancellation_reason: item.cancellationReason ?? null, completed_at: item.completedAt ?? null, created_at: item.createdAt, updated_at: item.updatedAt });

export class SurgeryRepository {
  constructor(private readonly sequenceService: SequenceService) {}
  session() { return mongoose.startSession(); }

  async acquireConcurrencyLock(doctorId: string, serviceId: string, session: ClientSession) {
    const locks = [
      { type: 'Doctor', id: doctorId },
      { type: 'Service', id: serviceId }
    ].sort((a, b) => a.id.localeCompare(b.id));

    for (const lock of locks) {
      if (lock.type === 'Doctor') {
        await DoctorModel.updateOne({ _id: oid(lock.id) }, { $set: { updatedAt: new Date() } }, { session });
      } else {
        await ServiceModel.updateOne({ _id: oid(lock.id) }, { $set: { updatedAt: new Date() } }, { session });
      }
    }
  }

  async hasBranchAccess(userId: string, branchId: string) { const [user, branch] = await Promise.all([UserModel.findOne({ _id: userId, status: 'active', deletedAt: null }).select('branchIds roleIds').lean(), BranchModel.exists({ _id: branchId, status: 'ACTIVE', deletedAt: null })]); if (!user || !branch) return false; if ((user.branchIds ?? []).some((id) => id.toString() === branchId)) return true; return Boolean(await RoleModel.exists({ _id: { $in: user.roleIds ?? [] }, code: 'SUPER_ADMIN', status: 'active', deletedAt: null })); }
  async departmentScope(userId: string) { const user = await UserModel.findOne({ _id: oid(userId), status: 'active', deletedAt: null }).select('departmentIds roleIds').lean(); if (!user) return []; const superAdmin = await RoleModel.exists({ _id: { $in: user.roleIds ?? [] }, code: 'SUPER_ADMIN', status: 'active', deletedAt: null }); return superAdmin ? undefined : (user.departmentIds ?? []).map((id) => id.toString()); }
  async recommendationReferences(data: CreateProcedureRecommendationDTO, session: ClientSession) { const patient = await PatientModel.findOne({ _id: oid(data.patient_id), status: 'ACTIVE', deletedAt: null }).session(session).lean(); const doctor = await DoctorModel.findOne({ _id: oid(data.recommending_doctor_id), branchId: oid(data.branch_id), departmentId: oid(data.department_id), status: 'ACTIVE', deletedAt: null }).session(session).lean(); const department = await DepartmentModel.findOne({ _id: oid(data.department_id), branchIds: oid(data.branch_id), status: 'ACTIVE', deletedAt: null }).session(session).lean(); const service = await ServiceModel.findOne({ _id: oid(data.service_id), departmentId: oid(data.department_id), serviceType: 'PROCEDURE', status: 'ACTIVE', deletedAt: null }).session(session).lean(); const encounter = await OpdVisitModel.findOne({ _id: oid(data.encounter_id), patientId: oid(data.patient_id), doctorId: oid(data.recommending_doctor_id), branchId: oid(data.branch_id), departmentId: oid(data.department_id), deletedAt: null }).session(session).lean(); return { patient, doctor, department, service, encounter }; }
  async createRecommendation(data: CreateProcedureRecommendationDTO, refs: { patientNumber: string; patientName: string; doctorName: string; departmentName: string; serviceName: string }, actor: string, session: ClientSession) { const sequence = await this.sequenceService.getNextSequence('surgery_recommendation', session); const rows = await ProcedureRecommendationModel.create([{ recommendationNumber: this.sequenceService.formatTimestampSequence('PR', sequence), patientId: oid(data.patient_id), patientNumber: refs.patientNumber, patientName: refs.patientName, branchId: oid(data.branch_id), departmentId: oid(data.department_id), departmentName: refs.departmentName, recommendingDoctorId: oid(data.recommending_doctor_id), recommendingDoctorName: refs.doctorName, serviceId: oid(data.service_id), serviceName: refs.serviceName, encounterType: data.encounter_type, encounterId: oid(data.encounter_id), clinicalReason: data.clinical_reason, notes: data.notes ?? null, status: 'ACTIVE', createdBy: oid(actor), updatedBy: oid(actor) }], { session }); const row = rows[0]; if (!row) throw new Error('Recommendation create returned no record'); return recommendationDto(row.toObject() as RecommendationLean); }
  async listRecommendations(query: SurgeryListQuery, departmentIds?: string[]) { const page = query.page ?? 1; const limit = query.limit ?? 20; const filter: Record<string, unknown> = { branchId: oid(query.branch_id), ...(departmentIds ? { departmentId: { $in: departmentIds.map(oid) } } : {}) }; if (query.status) filter.status = query.status; if (query.patient_id) filter.patientId = oid(query.patient_id); if (query.service_id) filter.serviceId = oid(query.service_id); if (query.search) { const value = new RegExp(query.search.replace(/[.*+?^${}()|[\]\\]/g, '\\$&'), 'i'); filter.$or = [{ recommendationNumber: value }, { patientName: value }, { patientNumber: value }, { serviceName: value }]; } const [rows, total] = await Promise.all([ProcedureRecommendationModel.find(filter).sort({ createdAt: -1 }).skip((page - 1) * limit).limit(limit).lean<RecommendationLean[]>(), ProcedureRecommendationModel.countDocuments(filter)]); return { data: rows.map(recommendationDto), meta: paging(total, page, limit) }; }
  async getRecommendation(id: string, branchId: string, session?: ClientSession) { const q = ProcedureRecommendationModel.findOne({ _id: oid(id), branchId: oid(branchId) }).lean<RecommendationLean>(); if (session) q.session(session); const row = await q; return row ? recommendationDto(row) : null; }
  async cancelRecommendation(id: string, branchId: string, reason: string, actor: string, session: ClientSession) { const row = await ProcedureRecommendationModel.findOneAndUpdate({ _id: oid(id), branchId: oid(branchId), status: 'ACTIVE', bookingId: null }, { $set: { status: 'CANCELLED', cancellationReason: reason, cancelledAt: new Date(), cancelledBy: oid(actor), updatedBy: oid(actor) } }, { new: true, session }).lean<RecommendationLean>(); return row ? recommendationDto(row) : null; }
  async getActiveRecommendationRecord(id: string, branchId: string, session: ClientSession) { return ProcedureRecommendationModel.findOne({ _id: oid(id), branchId: oid(branchId), status: 'ACTIVE', bookingId: null }).session(session).lean<RecommendationLean>(); }
  async bookingReferences(recommendation: RecommendationLean, doctorId: string, session: ClientSession) { const service = await ServiceModel.findOne({ _id: recommendation.serviceId, serviceType: 'PROCEDURE', status: 'ACTIVE', deletedAt: null }).session(session).lean(); const doctor = await DoctorModel.findOne({ _id: oid(doctorId), branchId: recommendation.branchId, departmentId: recommendation.departmentId, status: 'ACTIVE', deletedAt: null }).session(session).lean(); return { service, doctor }; }
  async getProcedureService(id: string) { return ServiceModel.findOne({ _id: oid(id), serviceType: 'PROCEDURE', status: 'ACTIVE', deletedAt: null }).lean(); }
  async createBooking(data: CreateProcedureBookingDTO, recommendation: RecommendationLean, refs: { doctorName: string; duration: number }, actor: string, session: ClientSession) { const start = new Date(data.scheduled_start); const end = new Date(start.getTime() + refs.duration * 60000); const sequence = await this.sequenceService.getNextSequence('surgery_booking', session); const rows = await ProcedureBookingModel.create([{ bookingNumber: this.sequenceService.formatTimestampSequence('PB', sequence), recommendationId: recommendation._id, patientId: recommendation.patientId, patientNumber: recommendation.patientNumber, patientName: recommendation.patientName, branchId: recommendation.branchId, departmentId: recommendation.departmentId, departmentName: recommendation.departmentName, serviceId: recommendation.serviceId, serviceName: recommendation.serviceName, doctorId: oid(data.doctor_id), doctorName: refs.doctorName, scheduledStart: start, scheduledEnd: end, durationMinutes: refs.duration, status: 'PENDING_CONFIRMATION', holdId: data.hold_id ? oid(data.hold_id) : null, consentDocumentId: data.consent_document_id ? oid(data.consent_document_id) : null, depositInvoiceId: data.deposit_invoice_id ? oid(data.deposit_invoice_id) : null, notes: data.notes ?? null, createdBy: oid(actor), updatedBy: oid(actor) }], { session }); const row = rows[0]; if (!row) throw new Error('Booking create returned no record'); return bookingDto(row.toObject() as BookingLean); }
  async getBookingRecord(id: string, branchId: string, session?: ClientSession) { const q = ProcedureBookingModel.findOne({ _id: oid(id), branchId: oid(branchId) }).lean<BookingLean>(); if (session) q.session(session); return session ? q.session(session) : q; }
  async getBooking(id: string, branchId: string) { const row = await this.getBookingRecord(id, branchId); return row ? bookingDto(row) : null; }
  async listBookings(query: SurgeryListQuery, departmentIds?: string[]) { const page = query.page ?? 1; const limit = query.limit ?? 20; const filter: Record<string, unknown> = { branchId: oid(query.branch_id), ...(departmentIds ? { departmentId: { $in: departmentIds.map(oid) } } : {}) }; if (query.status) filter.status = query.status; if (query.patient_id) filter.patientId = oid(query.patient_id); if (query.doctor_id) filter.doctorId = oid(query.doctor_id); if (query.service_id) filter.serviceId = oid(query.service_id); if (query.from || query.to) filter.scheduledStart = { ...(query.from ? { $gte: new Date(query.from) } : {}), ...(query.to ? { $lte: new Date(query.to) } : {}) }; if (query.search) { const value = new RegExp(query.search.replace(/[.*+?^${}()|[\]\\]/g, '\\$&'), 'i'); filter.$or = [{ bookingNumber: value }, { patientName: value }, { patientNumber: value }, { serviceName: value }, { doctorName: value }]; } const [rows, total] = await Promise.all([ProcedureBookingModel.find(filter).sort({ scheduledStart: 1 }).skip((page - 1) * limit).limit(limit).lean<BookingLean[]>(), ProcedureBookingModel.countDocuments(filter)]); return { data: rows.map(bookingDto), meta: paging(total, page, limit) }; }
  async countServiceOverlap(serviceId: string, start: Date, end: Date, excludeId?: string, session?: ClientSession) { const filter: Record<string, unknown> = { serviceId: oid(serviceId), status: { $in: ['PENDING_CONFIRMATION', 'BOOKED'] }, scheduledStart: { $lt: end }, scheduledEnd: { $gt: start } }; if (excludeId) filter._id = { $ne: oid(excludeId) }; const q = ProcedureBookingModel.countDocuments(filter); if (session) q.session(session); return q; }
  async hasDoctorOverlap(doctorId: string, start: Date, end: Date, excludeId?: string, session?: ClientSession) { const filter: Record<string, unknown> = { doctorId: oid(doctorId), status: { $in: ['PENDING_CONFIRMATION', 'BOOKED'] }, scheduledStart: { $lt: end }, scheduledEnd: { $gt: start } }; if (excludeId) filter._id = { $ne: oid(excludeId) }; const q = ProcedureBookingModel.exists(filter); if (session) q.session(session); return Boolean(await q); }
  async hasAppointmentOverlap(doctorId: string, start: Date, end: Date, session?: ClientSession) { const dayStart = new Date(Date.UTC(start.getUTCFullYear(), start.getUTCMonth(), start.getUTCDate())); const startTime = start.toISOString().slice(11, 16); const endTime = end.toISOString().slice(11, 16); const q = AppointmentModel.exists({ doctorId: oid(doctorId), appointmentDate: dayStart, status: { $in: ['SCHEDULED', 'CONFIRMED', 'CHECKED_IN'] }, startTime: { $lt: endTime }, endTime: { $gt: startTime }, deletedAt: null }); if (session) q.session(session); return Boolean(await q); }
  async validateHold(holdId: string, patientId: string, branchId: string, session: ClientSession) { return BedHoldModel.findOne({ _id: oid(holdId), patientId: oid(patientId), branchId: oid(branchId), status: 'ACTIVE', expiresAt: { $gt: new Date() } }).session(session).lean(); }
  async markRecommendationBooked(id: string, bookingId: string, actor: string, session: ClientSession) { return ProcedureRecommendationModel.findOneAndUpdate({ _id: oid(id), status: 'ACTIVE', bookingId: null }, { $set: { status: 'BOOKED', bookingId: oid(bookingId), updatedBy: oid(actor) } }, { new: true, session }); }
  async confirmBooking(id: string, branchId: string, data: { holdId: string | null; consentId: string | null; invoiceId: string | null; snapshot: Record<string, unknown> }, actor: string, session: ClientSession) { const row = await ProcedureBookingModel.findOneAndUpdate({ _id: oid(id), branchId: oid(branchId), status: 'PENDING_CONFIRMATION' }, { $set: { status: 'BOOKED', holdId: data.holdId ? oid(data.holdId) : null, consentDocumentId: data.consentId ? oid(data.consentId) : null, depositInvoiceId: data.invoiceId ? oid(data.invoiceId) : null, prerequisiteSnapshot: data.snapshot, updatedBy: oid(actor) } }, { new: true, session }).lean<BookingLean>(); return row ? bookingDto(row) : null; }
  async rescheduleBooking(record: BookingLean, start: Date, end: Date, doctorId: string, doctorName: string, reason: string, holdId: string | null, actor: string, session: ClientSession) { const row = await ProcedureBookingModel.findOneAndUpdate({ _id: record._id, status: 'BOOKED', scheduledStart: record.scheduledStart, scheduledEnd: record.scheduledEnd }, { $set: { scheduledStart: start, scheduledEnd: end, doctorId: oid(doctorId), doctorName, holdId: holdId ? oid(holdId) : null, updatedBy: oid(actor) }, $push: { scheduleHistory: { previousStart: record.scheduledStart, previousEnd: record.scheduledEnd, newStart: start, newEnd: end, previousDoctorId: record.doctorId, newDoctorId: oid(doctorId), reason, changedBy: oid(actor), changedAt: new Date() } } }, { new: true, session }).lean<BookingLean>(); return row ? bookingDto(row) : null; }
  async cancelBooking(id: string, branchId: string, reason: string, actor: string, session: ClientSession) { const row = await ProcedureBookingModel.findOneAndUpdate({ _id: oid(id), branchId: oid(branchId), status: { $in: ['PENDING_CONFIRMATION', 'BOOKED'] } }, { $set: { status: 'CANCELLED', cancellationReason: reason, cancelledAt: new Date(), cancelledBy: oid(actor), updatedBy: oid(actor) } }, { new: true, session }).lean<BookingLean>(); return row ? bookingDto(row) : null; }
  async completeBooking(id: string, branchId: string, actor: string, session: ClientSession) { const row = await ProcedureBookingModel.findOneAndUpdate({ _id: oid(id), branchId: oid(branchId), status: 'BOOKED', scheduledStart: { $lte: new Date() } }, { $set: { status: 'COMPLETED', completedAt: new Date(), completedBy: oid(actor), updatedBy: oid(actor) } }, { new: true, session }).lean<BookingLean>(); return row ? bookingDto(row) : null; }
  async audit(eventType: string, actor: string, metadata: SurgeryMetadata, details: Record<string, unknown>, session: ClientSession) { await AuditLogModel.create([{ eventType, actorUserId: actor, ipAddress: metadata.ipAddress, userAgent: metadata.userAgent, metadataJson: details }], { session }); }
}
