import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { branchesApi } from '../api/branches';
import { departmentsApi } from '../api/departments';
import { doctorsApi } from '../api/doctors';
import { patientsApi } from '../api/patients';
import { admissionsConfigurationApi } from '../api/admissions-configuration';
import { inpatientAdmissionsService } from '../services/inpatient-admissions.service';
import type { AdmissionPayload } from '../api/inpatient-admissions';
export const useInpatientAdmissions = (branchId: string, patientSearch: string) => { const client = useQueryClient(); const branches = useQuery({ queryKey: ['admissions', 'branches'], queryFn: () => branchesApi.list({ status: 'ACTIVE', page: 1, limit: 100 }), }); const patients = useQuery({ queryKey: ['admissions', 'patients', patientSearch], queryFn: () => patientsApi.list({ search: patientSearch, status: 'ACTIVE', page: 1, limit: 20 }), enabled: patientSearch.length >= 2 }); const doctors = useQuery({ queryKey: ['admissions', 'doctors', branchId], queryFn: () => doctorsApi.list({ branch_id: branchId, status: 'ACTIVE', page: 1, limit: 100 }), enabled: Boolean(branchId) }); const departments = useQuery({ queryKey: ['admissions', 'departments', branchId], queryFn: () => departmentsApi.list({ branch_id: branchId, status: 'ACTIVE', page: 1, limit: 100 }), enabled: Boolean(branchId) }); const wards = useQuery({ queryKey: ['admissions', 'wards', branchId], queryFn: () => admissionsConfigurationApi.wards({ branch_id: branchId, status: 'ACTIVE', page: 1, limit: 100 }), enabled: Boolean(branchId) }); const beds = useQuery({ queryKey: ['admissions', 'available-beds', branchId], queryFn: () => admissionsConfigurationApi.beds({ branch_id: branchId, status: 'AVAILABLE', page: 1, limit: 100 }), enabled: Boolean(branchId) }); const admissions = useQuery({ queryKey: ['admissions', 'inpatients', branchId], queryFn: () => inpatientAdmissionsService.list({ branch_id: branchId, page: 1, limit: 20 }), enabled: Boolean(branchId) }); const create = useMutation({ mutationFn: (payload: AdmissionPayload) => inpatientAdmissionsService.create(payload), onSuccess: () => { void client.invalidateQueries({ queryKey: ['admissions', 'inpatients'] }); void client.invalidateQueries({ queryKey: ['admissions', 'available-beds'] }); } }); return { branches, patients, doctors, departments, wards, beds, admissions, create }; };
