import type { FastifyInstance, FastifyRequest } from 'fastify';
import { ZodError } from 'zod';
import { requirePermission } from '../../middleware/require-permission.js';
import { AppError } from '../../shared/errors/app-error.js';
import { ok } from '../../shared/http/response.js';
import type { ServiceRegistry } from '../../shared/types/service-registry.js';
import { admissionPolicySchema, bedBodySchema, bedListSchema, bedStatusSchema, cancelBedTransferSchema, closeBedHoldSchema, completeBedTransferSchema, createBedHoldSchema, createBedTransferSchema, idParamsSchema, updateBedBodySchema, wardBodySchema, wardListSchema, wardStatusSchema } from './admissions-configuration.schemas.js';

const metadata = (request: FastifyRequest) => ({ ipAddress: request.ip, userAgent: request.headers['user-agent'] });
const parse = <T>(schema: { parse(value: unknown): T }, value: unknown) => {
  try {
    return schema.parse(value);
  } catch (error) {
    if (error instanceof ZodError) {
      throw new AppError('Request validation failed', 400, 'VALIDATION_ERROR', error.flatten());
    }
    throw error;
  }
};
export const registerAdmissionsConfigurationRoutes = async (app: FastifyInstance, services: ServiceRegistry) => {
  app.get('/api/admissions/wards', { preHandler: requirePermission(services, 'Admissions', 'Wards', 'View') }, async (request) => ok(await services.admissionsConfiguration.listWards(parse(wardListSchema, request.query), request.user!.id)));
  app.get('/api/admissions/wards/:id', { preHandler: requirePermission(services, 'Admissions', 'Wards', 'View') }, async (request) => { const params = parse(idParamsSchema, request.params); const query = parse(wardListSchema.pick({ branch_id: true }), request.query); return ok(await services.admissionsConfiguration.getWard(params.id, query.branch_id, request.user!.id)); });
  app.post('/api/admissions/wards', { preHandler: requirePermission(services, 'Admissions', 'Wards', 'Create') }, async (request, reply) => reply.status(201).send(ok(await services.admissionsConfiguration.createWard(parse(wardBodySchema, request.body), request.user!.id, metadata(request)))));
  app.patch('/api/admissions/wards/:id', { preHandler: requirePermission(services, 'Admissions', 'Wards', 'Edit') }, async (request) => { const params = parse(idParamsSchema, request.params); return ok(await services.admissionsConfiguration.updateWard(params.id, parse(wardBodySchema, request.body), request.user!.id, metadata(request))); });
  app.patch('/api/admissions/wards/:id/status', { preHandler: requirePermission(services, 'Admissions', 'Wards', 'ChangeStatus') }, async (request) => { const params = parse(idParamsSchema, request.params); const body = parse(wardStatusSchema, request.body); return ok(await services.admissionsConfiguration.updateWardStatus(params.id, body.branch_id, body.status, request.user!.id, metadata(request))); });
  app.get('/api/admissions/beds/summary', { preHandler: requirePermission(services, 'Admissions', 'Beds', 'View') }, async (request) => { const query = parse(wardListSchema.pick({ branch_id: true }), request.query); return ok(await services.admissionsConfiguration.summary(query.branch_id, request.user!.id, metadata(request))); });
  app.get('/api/admissions/beds', { preHandler: requirePermission(services, 'Admissions', 'Beds', 'View') }, async (request) => ok(await services.admissionsConfiguration.listBeds(parse(bedListSchema, request.query), request.user!.id, metadata(request))));
  app.get('/api/admissions/beds/:id', { preHandler: requirePermission(services, 'Admissions', 'Beds', 'View') }, async (request) => { const params = parse(idParamsSchema, request.params); const query = parse(wardListSchema.pick({ branch_id: true }), request.query); return ok(await services.admissionsConfiguration.getBed(params.id, query.branch_id, request.user!.id, metadata(request))); });
  app.post('/api/admissions/beds', { preHandler: requirePermission(services, 'Admissions', 'Beds', 'Create') }, async (request, reply) => reply.status(201).send(ok(await services.admissionsConfiguration.createBed(parse(bedBodySchema, request.body), request.user!.id, metadata(request)))));
  app.patch('/api/admissions/beds/:id', { preHandler: requirePermission(services, 'Admissions', 'Beds', 'Edit') }, async (request) => { const params = parse(idParamsSchema, request.params); const body = parse(updateBedBodySchema, request.body); return ok(await services.admissionsConfiguration.updateBed(params.id, body, request.user!.id, metadata(request))); });
  app.patch('/api/admissions/beds/:id/status', { preHandler: requirePermission(services, 'Admissions', 'Beds', 'ChangeStatus') }, async (request) => { const params = parse(idParamsSchema, request.params); const body = parse(bedStatusSchema, request.body); return ok(await services.admissionsConfiguration.updateBedStatus(params.id, body.branch_id, body.status, body.reason ?? null, request.user!.id, metadata(request))); });
  app.get('/api/admissions/policy', { preHandler: requirePermission(services, 'Admissions', 'Admission Policy', 'View') }, async (request) => { const query = parse(wardListSchema.pick({ branch_id: true }), request.query); return ok(await services.admissionsConfiguration.getPolicy(query.branch_id, request.user!.id)); });
  app.put('/api/admissions/policy', { preHandler: requirePermission(services, 'Admissions', 'Admission Policy', 'Edit') }, async (request) => ok(await services.admissionsConfiguration.savePolicy(parse(admissionPolicySchema, request.body), request.user!.id, metadata(request))));
  app.post('/api/admissions/beds/:id/holds', { preHandler: requirePermission(services, 'Admissions', 'Bed Holds', 'Create') }, async (request, reply) => { const params = parse(idParamsSchema, request.params); return reply.status(201).send(ok(await services.admissionsConfiguration.createHold(params.id, parse(createBedHoldSchema, request.body), request.user!.id, metadata(request)))); });
  app.post('/api/admissions/bed-holds/:id/release', { preHandler: requirePermission(services, 'Admissions', 'Bed Holds', 'Release') }, async (request) => { const params = parse(idParamsSchema, request.params); return ok(await services.admissionsConfiguration.closeHold(params.id, parse(closeBedHoldSchema, request.body), 'RELEASED', request.user!.id, metadata(request))); });
  app.post('/api/admissions/bed-holds/:id/cancel', { preHandler: requirePermission(services, 'Admissions', 'Bed Holds', 'Cancel') }, async (request) => { const params = parse(idParamsSchema, request.params); return ok(await services.admissionsConfiguration.closeHold(params.id, parse(closeBedHoldSchema, request.body), 'CANCELLED', request.user!.id, metadata(request))); });
  app.post('/api/admissions/inpatients/:id/transfers', { preHandler: requirePermission(services, 'Admissions', 'Bed Transfers', 'Create') }, async (request, reply) => { const params = parse(idParamsSchema, request.params); return reply.status(201).send(ok(await services.admissionsConfiguration.createTransfer(params.id, parse(createBedTransferSchema, request.body), request.user!.id, metadata(request), false))); });
  app.post('/api/admissions/inpatients/:id/cross-branch-transfers', { preHandler: [...requirePermission(services, 'Admissions', 'Bed Transfers', 'Create'), ...requirePermission(services, 'Admissions', 'Bed Transfers', 'CrossBranch')] }, async (request, reply) => { const params = parse(idParamsSchema, request.params); return reply.status(201).send(ok(await services.admissionsConfiguration.createTransfer(params.id, parse(createBedTransferSchema, request.body), request.user!.id, metadata(request), true))); });
  app.post('/api/admissions/bed-transfers/:id/complete', { preHandler: requirePermission(services, 'Admissions', 'Bed Transfers', 'Complete') }, async (request) => { const params = parse(idParamsSchema, request.params); return ok(await services.admissionsConfiguration.completeTransfer(params.id, parse(completeBedTransferSchema, request.body), request.user!.id, metadata(request), false)); });
  app.post('/api/admissions/bed-transfers/:id/complete-cross-branch', { preHandler: [...requirePermission(services, 'Admissions', 'Bed Transfers', 'Complete'), ...requirePermission(services, 'Admissions', 'Bed Transfers', 'CrossBranch')] }, async (request) => { const params = parse(idParamsSchema, request.params); return ok(await services.admissionsConfiguration.completeTransfer(params.id, parse(completeBedTransferSchema, request.body), request.user!.id, metadata(request), true)); });
  app.post('/api/admissions/bed-transfers/:id/cancel', { preHandler: requirePermission(services, 'Admissions', 'Bed Transfers', 'Cancel') }, async (request) => { const params = parse(idParamsSchema, request.params); return ok(await services.admissionsConfiguration.cancelTransfer(params.id, parse(cancelBedTransferSchema, request.body), request.user!.id, metadata(request))); });
};
