import mongoose, { Schema, Types } from 'mongoose';
import type { BedHoldStatus, BedStatus, BedTransferStatus, WardStatus } from './admissions-configuration.types.js';

export type WardFields = { branchId: Types.ObjectId; name: string; wardType: string; floor: string; description?: string | null; status: WardStatus; createdBy: Types.ObjectId; updatedBy: Types.ObjectId; createdAt: Date; updatedAt: Date };
export type BedFields = { branchId: Types.ObjectId; wardId: Types.ObjectId; bedNumber: string; bedCategory: string; roomNumber?: string | null; status: BedStatus; blockReasonCode?: string | null; currentHoldId?: Types.ObjectId | null; currentAdmissionId?: Types.ObjectId | null; version: number; createdBy: Types.ObjectId; updatedBy: Types.ObjectId; createdAt: Date; updatedAt: Date };
export type AdmissionPolicyFields = { branchId: Types.ObjectId; bedHoldDurationMinutes: number; admissionConsentRequired: boolean; admissionAdvanceDepositRequired: boolean; admissionMinimumDepositAmount: number; status: 'ACTIVE' | 'INACTIVE'; version: number; createdBy: Types.ObjectId; updatedBy: Types.ObjectId; createdAt: Date; updatedAt: Date };
export type BedHoldFields = { holdNumber: string; idempotencyKey: string; requestHash: string; patientId: Types.ObjectId; branchId: Types.ObjectId; wardId: Types.ObjectId; bedId: Types.ObjectId; admissionId?: Types.ObjectId | null; wardName: string; bedNumber: string; bedCategory: string; roomNumber?: string | null; status: BedHoldStatus; heldAt: Date; expiresAt: Date; reason: string; terminalReason?: string | null; version: number; createdBy: Types.ObjectId; updatedBy: Types.ObjectId; releasedBy?: Types.ObjectId | null; releasedAt?: Date | null; cancelledBy?: Types.ObjectId | null; cancelledAt?: Date | null; consumedBy?: Types.ObjectId | null; consumedAt?: Date | null; createdAt: Date; updatedAt: Date };
export type BedAssignmentHistoryFields = { admissionId: Types.ObjectId; patientId: Types.ObjectId; branchId: Types.ObjectId; wardId: Types.ObjectId; bedId: Types.ObjectId; wardName: string; bedNumber: string; bedCategory: string; roomNumber?: string | null; eventType: 'ALLOTTED' | 'TRANSFERRED_OUT' | 'TRANSFERRED_IN' | 'RELEASED'; reason: string; transferId?: Types.ObjectId | null; occurredAt: Date; actorUserId: Types.ObjectId; createdAt: Date; updatedAt: Date };
export type BedTransferFields = { admissionId: Types.ObjectId; patientId: Types.ObjectId; sourceBranchId: Types.ObjectId; sourceWardId: Types.ObjectId; sourceBedId: Types.ObjectId; destinationBranchId: Types.ObjectId; destinationWardId: Types.ObjectId; destinationBedId: Types.ObjectId; sourceWardName: string; sourceBedNumber: string; sourceRoomNumber?: string | null; destinationWardName: string; destinationBedNumber: string; destinationRoomNumber?: string | null; reason: string; status: BedTransferStatus; requestedAt: Date; requestedBy: Types.ObjectId; completedAt?: Date | null; completedBy?: Types.ObjectId | null; cancelledAt?: Date | null; cancelledBy?: Types.ObjectId | null; cancellationReason?: string | null; version: number; createdAt: Date; updatedAt: Date };

const audit = { createdBy: { type: Schema.Types.ObjectId, ref: 'User', required: true }, updatedBy: { type: Schema.Types.ObjectId, ref: 'User', required: true } } as const;
const wardSchema = new Schema<WardFields>({ branchId: { type: Schema.Types.ObjectId, ref: 'Branch', required: true }, name: { type: String, required: true, trim: true }, wardType: { type: String, required: true, trim: true }, floor: { type: String, required: true, trim: true }, description: { type: String, default: null, trim: true }, status: { type: String, enum: ['ACTIVE', 'INACTIVE'], default: 'ACTIVE', required: true }, ...audit }, { timestamps: true });
const bedSchema = new Schema<BedFields>({ branchId: { type: Schema.Types.ObjectId, ref: 'Branch', required: true }, wardId: { type: Schema.Types.ObjectId, ref: 'HmsWard', required: true }, bedNumber: { type: String, required: true, trim: true, uppercase: true }, bedCategory: { type: String, required: true, trim: true }, roomNumber: { type: String, default: null, trim: true }, status: { type: String, enum: ['AVAILABLE', 'OCCUPIED', 'RESERVED', 'BLOCKED', 'UNDER_MAINTENANCE', 'INACTIVE'], default: 'AVAILABLE', required: true }, blockReasonCode: { type: String, default: null, trim: true, uppercase: true }, currentHoldId: { type: Schema.Types.ObjectId, ref: 'BedHold', default: null }, currentAdmissionId: { type: Schema.Types.ObjectId, ref: 'InpatientAdmission', default: null }, version: { type: Number, default: 0, min: 0, required: true }, ...audit }, { timestamps: true });
const admissionPolicySchema = new Schema<AdmissionPolicyFields>({ branchId: { type: Schema.Types.ObjectId, ref: 'Branch', required: true }, bedHoldDurationMinutes: { type: Number, min: 5, max: 240, required: true }, admissionConsentRequired: { type: Boolean, required: true }, admissionAdvanceDepositRequired: { type: Boolean, required: true }, admissionMinimumDepositAmount: { type: Number, min: 0, required: true }, status: { type: String, enum: ['ACTIVE', 'INACTIVE'], default: 'ACTIVE', required: true }, version: { type: Number, default: 0, min: 0, required: true }, ...audit }, { timestamps: true });
const bedHoldSchema = new Schema<BedHoldFields>({ holdNumber: { type: String, required: true, unique: true }, idempotencyKey: { type: String, required: true, unique: true }, requestHash: { type: String, required: true }, patientId: { type: Schema.Types.ObjectId, ref: 'Patient', required: true }, branchId: { type: Schema.Types.ObjectId, ref: 'Branch', required: true }, wardId: { type: Schema.Types.ObjectId, ref: 'HmsWard', required: true }, bedId: { type: Schema.Types.ObjectId, ref: 'HmsBed', required: true }, admissionId: { type: Schema.Types.ObjectId, ref: 'InpatientAdmission', default: null }, wardName: { type: String, required: true }, bedNumber: { type: String, required: true }, bedCategory: { type: String, required: true }, roomNumber: { type: String, default: null }, status: { type: String, enum: ['ACTIVE', 'CONSUMED', 'RELEASED', 'EXPIRED', 'CANCELLED'], required: true }, heldAt: { type: Date, required: true }, expiresAt: { type: Date, required: true }, reason: { type: String, required: true }, terminalReason: { type: String, default: null }, version: { type: Number, default: 0, min: 0, required: true }, createdBy: { type: Schema.Types.ObjectId, ref: 'User', required: true }, updatedBy: { type: Schema.Types.ObjectId, ref: 'User', required: true }, releasedBy: { type: Schema.Types.ObjectId, ref: 'User', default: null }, releasedAt: { type: Date, default: null }, cancelledBy: { type: Schema.Types.ObjectId, ref: 'User', default: null }, cancelledAt: { type: Date, default: null }, consumedBy: { type: Schema.Types.ObjectId, ref: 'User', default: null }, consumedAt: { type: Date, default: null } }, { timestamps: true });
const assignmentHistorySchema = new Schema<BedAssignmentHistoryFields>({ admissionId: { type: Schema.Types.ObjectId, ref: 'InpatientAdmission', required: true }, patientId: { type: Schema.Types.ObjectId, ref: 'Patient', required: true }, branchId: { type: Schema.Types.ObjectId, ref: 'Branch', required: true }, wardId: { type: Schema.Types.ObjectId, ref: 'HmsWard', required: true }, bedId: { type: Schema.Types.ObjectId, ref: 'HmsBed', required: true }, wardName: { type: String, required: true }, bedNumber: { type: String, required: true }, bedCategory: { type: String, required: true }, roomNumber: { type: String, default: null }, eventType: { type: String, enum: ['ALLOTTED', 'TRANSFERRED_OUT', 'TRANSFERRED_IN', 'RELEASED'], required: true }, reason: { type: String, required: true }, transferId: { type: Schema.Types.ObjectId, ref: 'BedTransfer', default: null }, occurredAt: { type: Date, required: true }, actorUserId: { type: Schema.Types.ObjectId, ref: 'User', required: true } }, { timestamps: true });
const bedTransferSchema = new Schema<BedTransferFields>({ admissionId: { type: Schema.Types.ObjectId, ref: 'InpatientAdmission', required: true }, patientId: { type: Schema.Types.ObjectId, ref: 'Patient', required: true }, sourceBranchId: { type: Schema.Types.ObjectId, ref: 'Branch', required: true }, sourceWardId: { type: Schema.Types.ObjectId, ref: 'HmsWard', required: true }, sourceBedId: { type: Schema.Types.ObjectId, ref: 'HmsBed', required: true }, destinationBranchId: { type: Schema.Types.ObjectId, ref: 'Branch', required: true }, destinationWardId: { type: Schema.Types.ObjectId, ref: 'HmsWard', required: true }, destinationBedId: { type: Schema.Types.ObjectId, ref: 'HmsBed', required: true }, sourceWardName: { type: String, required: true }, sourceBedNumber: { type: String, required: true }, sourceRoomNumber: { type: String, default: null }, destinationWardName: { type: String, required: true }, destinationBedNumber: { type: String, required: true }, destinationRoomNumber: { type: String, default: null }, reason: { type: String, required: true }, status: { type: String, enum: ['PENDING', 'COMPLETED', 'CANCELLED'], required: true }, requestedAt: { type: Date, required: true }, requestedBy: { type: Schema.Types.ObjectId, ref: 'User', required: true }, completedAt: { type: Date, default: null }, completedBy: { type: Schema.Types.ObjectId, ref: 'User', default: null }, cancelledAt: { type: Date, default: null }, cancelledBy: { type: Schema.Types.ObjectId, ref: 'User', default: null }, cancellationReason: { type: String, default: null }, version: { type: Number, default: 0, min: 0, required: true } }, { timestamps: true });
wardSchema.index({ branchId: 1, name: 1 }, { unique: true });
wardSchema.index({ branchId: 1, status: 1, floor: 1 });
bedSchema.index({ branchId: 1, wardId: 1, bedNumber: 1 }, { unique: true });
bedSchema.index({ branchId: 1, status: 1, wardId: 1 });
bedSchema.index({ branchId: 1, bedCategory: 1, roomNumber: 1 });
bedSchema.index({ currentHoldId: 1 }, { unique: true, partialFilterExpression: { currentHoldId: { $type: 'objectId' } } });
bedSchema.index({ currentAdmissionId: 1 }, { unique: true, partialFilterExpression: { currentAdmissionId: { $type: 'objectId' } } });
admissionPolicySchema.index({ branchId: 1, status: 1 }, { unique: true, partialFilterExpression: { status: 'ACTIVE' } });
bedHoldSchema.index({ bedId: 1, status: 1 }, { unique: true, partialFilterExpression: { status: 'ACTIVE' } });
bedHoldSchema.index({ status: 1, expiresAt: 1, branchId: 1 });
bedHoldSchema.index({ patientId: 1, status: 1, createdAt: -1 });
assignmentHistorySchema.index({ admissionId: 1, occurredAt: -1 });
assignmentHistorySchema.index({ bedId: 1, occurredAt: -1 });
bedTransferSchema.index({ admissionId: 1, status: 1, requestedAt: -1 });
bedTransferSchema.index({ destinationBedId: 1, status: 1 }, { unique: true, partialFilterExpression: { status: 'PENDING' } });

export const WardModel = mongoose.model<WardFields>('HmsWard', wardSchema);
export const BedModel = mongoose.model<BedFields>('HmsBed', bedSchema);
export const AdmissionPolicyModel = mongoose.model<AdmissionPolicyFields>('AdmissionPolicy', admissionPolicySchema);
export const BedHoldModel = mongoose.model<BedHoldFields>('BedHold', bedHoldSchema);
export const BedAssignmentHistoryModel = mongoose.model<BedAssignmentHistoryFields>('BedAssignmentHistory', assignmentHistorySchema);
export const BedTransferModel = mongoose.model<BedTransferFields>('BedTransfer', bedTransferSchema);
