export type WardStatus = 'ACTIVE' | 'INACTIVE';
export type BedStatus = 'AVAILABLE' | 'OCCUPIED' | 'RESERVED' | 'BLOCKED' | 'UNDER_MAINTENANCE' | 'INACTIVE';
export type BedHoldStatus = 'ACTIVE' | 'CONSUMED' | 'RELEASED' | 'EXPIRED' | 'CANCELLED';
export type BedTransferStatus = 'PENDING' | 'COMPLETED' | 'CANCELLED';

export type Ward = { id: string; branch_id: string; name: string; ward_type: string; floor: string; description: string | null; status: WardStatus; created_at: Date; updated_at: Date };
export type Bed = {
  id: string;
  branch_id: string;
  ward_id: string;
  ward_name: string;
  bed_number: string;
  bed_category: string;
  room_number: string | null;
  status: BedStatus;
  block_reason_code: string | null;
  current_hold_id: string | null;
  current_admission_id: string | null;
  hold_number: string | null;
  hold_expires_at: Date | null;
  admission_number: string | null;
  patient_id: string | null;
  patient_number: string | null;
  patient_name: string | null;
  version: number;
  created_at: Date;
  updated_at: Date;
};
export type PageMeta = { total: number; page: number; limit: number; totalPages: number };
export type WardListQuery = { branch_id: string; search?: string; ward_type?: string; floor?: string; status?: WardStatus; page?: number; limit?: number };
export type BedListQuery = { branch_id: string; ward_id?: string; search?: string; bed_category?: string; room_number?: string; status?: BedStatus; page?: number; limit?: number };
export type BedSummary = { total: number; available: number; occupied: number; reserved: number; blocked: number; under_maintenance: number; inactive: number };
export type AdmissionPolicy = {
  id: string;
  branch_id: string;
  bed_hold_duration_minutes: number;
  admission_consent_required: boolean;
  admission_advance_deposit_required: boolean;
  admission_minimum_deposit_amount: number;
  status: 'ACTIVE' | 'INACTIVE';
  version: number;
  created_at: Date;
  updated_at: Date;
};
export type SaveAdmissionPolicyDTO = {
  branch_id: string;
  bed_hold_duration_minutes: number;
  admission_consent_required: boolean;
  admission_advance_deposit_required: boolean;
  admission_minimum_deposit_amount: number;
};
export type BedHold = {
  id: string;
  hold_number: string;
  idempotency_key: string;
  patient_id: string;
  branch_id: string;
  ward_id: string;
  bed_id: string;
  admission_id: string | null;
  bed_number: string;
  ward_name: string;
  room_number: string | null;
  status: BedHoldStatus;
  held_at: Date;
  expires_at: Date;
  reason: string;
  terminal_reason: string | null;
  version: number;
  created_at: Date;
  updated_at: Date;
};
export type CreateBedHoldDTO = {
  branch_id: string;
  patient_id: string;
  admission_id?: string | null;
  reason: string;
  idempotency_key: string;
};
export type CloseBedHoldDTO = { branch_id: string; reason: string };
export type BedTransfer = {
  id: string;
  admission_id: string;
  patient_id: string;
  source_branch_id: string;
  source_ward_id: string;
  source_bed_id: string;
  destination_branch_id: string;
  destination_ward_id: string;
  destination_bed_id: string;
  source_bed_number: string;
  destination_bed_number: string;
  reason: string;
  status: BedTransferStatus;
  requested_at: Date;
  completed_at: Date | null;
  cancelled_at: Date | null;
  created_at: Date;
  updated_at: Date;
};
export type CreateBedTransferDTO = {
  branch_id: string;
  destination_branch_id: string;
  destination_ward_id: string;
  destination_bed_id: string;
  reason: string;
};
export type CompleteBedTransferDTO = { branch_id: string };
export type CancelBedTransferDTO = { branch_id: string; reason: string };
export type CreateWardDTO = { branch_id: string; name: string; ward_type: string; floor: string; description?: string | null };
export type UpdateWardDTO = Partial<Omit<CreateWardDTO, 'branch_id'>> & { branch_id: string };
export type CreateBedDTO = { ward_id: string; branch_id: string; bed_number: string; bed_category: string; bed_type?: string; charge_category?: string; gender_restriction?: BedGenderRestriction; room_number?: string | null };
export type UpdateBedDTO = Partial<Omit<CreateBedDTO, 'branch_id' | 'ward_id'>>;
export type StatusActionMetadata = { ipAddress?: string; userAgent?: string };
