import { AppError } from '../../shared/errors/app-error.js';
import type { AdmissionsConfigurationRepository } from './admissions-configuration.repository.js';
import type { BedFields } from './admissions-configuration.model.js';
import type { BedListQuery, CreateBedDTO, CreateWardDTO, StatusActionMetadata, UpdateBedDTO, UpdateWardDTO, WardListQuery } from './admissions-configuration.types.js';

export class AdmissionsConfigurationService {
  constructor(private readonly repository: AdmissionsConfigurationRepository) {}
  private async authorize(userId: string, branchId: string) { if (!await this.repository.hasBranchAccess(userId, branchId)) throw new AppError('Branch access denied', 403, 'BRANCH_ACCESS_DENIED'); }
  private duplicate(error: unknown): never { if (this.repository.duplicateError(error)) throw new AppError('A ward or bed with this identifier already exists in the selected scope', 409, 'DUPLICATE_CONFIGURATION'); throw error; }

  async listWards(query: WardListQuery, actor: string) { await this.authorize(actor, query.branch_id); return this.repository.listWards(query); }
  async getWard(id: string, branchId: string, actor: string) { await this.authorize(actor, branchId); const item = await this.repository.getWard(id, branchId); if (!item) throw new AppError('Ward not found', 404, 'WARD_NOT_FOUND'); return item; }
  async createWard(data: CreateWardDTO, actor: string, metadata: StatusActionMetadata) { await this.authorize(actor, data.branch_id); try { const ward = await this.repository.createWard(data, actor); await this.repository.audit('admissions.ward.created', actor, metadata, { wardId: ward.id, branchId: data.branch_id, newValue: ward }); return ward; } catch (error) { return this.duplicate(error); } }
  async updateWard(id: string, data: UpdateWardDTO, actor: string, metadata: StatusActionMetadata) { await this.authorize(actor, data.branch_id); const previous = await this.repository.getWard(id, data.branch_id); if (!previous) throw new AppError('Ward not found', 404, 'WARD_NOT_FOUND'); if (data.capacity) { const configuredBeds = await this.repository.countBedsForWard(id, data.branch_id); if (data.capacity < configuredBeds) throw new AppError('Ward capacity cannot be lower than its active configured bed count', 409, 'WARD_CAPACITY_BELOW_BED_COUNT'); } try { const ward = await this.repository.updateWard(id, data, actor); if (!ward) throw new AppError('Ward not found', 404, 'WARD_NOT_FOUND'); await this.repository.audit('admissions.ward.updated', actor, metadata, { wardId: id, branchId: data.branch_id, oldValue: previous, newValue: ward }); return ward; } catch (error) { return this.duplicate(error); } }
  async updateWardStatus(id: string, branchId: string, status: 'ACTIVE' | 'INACTIVE', actor: string, metadata: StatusActionMetadata) { await this.authorize(actor, branchId); const previous = await this.repository.getWard(id, branchId); if (!previous) throw new AppError('Ward not found', 404, 'WARD_NOT_FOUND'); const ward = await this.repository.updateWardStatus(id, branchId, status, actor); if (!ward) throw new AppError('Ward not found', 404, 'WARD_NOT_FOUND'); await this.repository.audit('admissions.ward.status_changed', actor, metadata, { wardId: id, branchId, oldValue: previous.status, newValue: status }); return ward; }

  async listBeds(query: BedListQuery, actor: string) { await this.authorize(actor, query.branch_id); return this.repository.listBeds(query); }
  async getBed(id: string, branchId: string, actor: string) { await this.authorize(actor, branchId); const item = await this.repository.getBed(id, branchId); if (!item) throw new AppError('Bed not found', 404, 'BED_NOT_FOUND'); return item; }
  async createBed(data: CreateBedDTO, actor: string, metadata: StatusActionMetadata) { await this.authorize(actor, data.branch_id); const ward = await this.repository.getWard(data.ward_id, data.branch_id); if (!ward) throw new AppError('Ward not found in selected branch', 404, 'WARD_NOT_FOUND'); if (ward.status !== 'ACTIVE') throw new AppError('Beds cannot be added to an inactive ward', 409, 'WARD_INACTIVE'); if (ward.capacity) { const configuredBeds = await this.repository.countBedsForWard(data.ward_id, data.branch_id); if (configuredBeds >= ward.capacity) throw new AppError('Ward capacity has been reached', 409, 'WARD_CAPACITY_REACHED'); } try { const bed = await this.repository.createBed(data, actor); if (!bed) throw new AppError('Bed could not be created', 500, 'BED_CREATE_FAILED'); await this.repository.audit('admissions.bed.created', actor, metadata, { bedId: bed.id, wardId: data.ward_id, branchId: data.branch_id, newValue: bed }); return bed; } catch (error) { return this.duplicate(error); } }
  async updateBed(id: string, data: UpdateBedDTO & { branch_id: string }, actor: string, metadata: StatusActionMetadata) { await this.authorize(actor, data.branch_id); const previous = await this.repository.getBed(id, data.branch_id); if (!previous) throw new AppError('Bed not found', 404, 'BED_NOT_FOUND'); if (previous.status === 'OCCUPIED' || previous.status === 'RESERVED') throw new AppError('An occupied or reserved bed cannot be edited as master data', 409, 'BED_OPERATIONAL_STATE'); try { const bed = await this.repository.updateBed(id, data.branch_id, data, actor); if (!bed) throw new AppError('Bed not found', 404, 'BED_NOT_FOUND'); await this.repository.audit('admissions.bed.updated', actor, metadata, { bedId: id, branchId: data.branch_id, oldValue: previous, newValue: bed }); return bed; } catch (error) { return this.duplicate(error); } }
  async updateBedStatus(id: string, branchId: string, status: BedFields['status'], actor: string, metadata: StatusActionMetadata) { await this.authorize(actor, branchId); const previous = await this.repository.getBed(id, branchId); if (!previous) throw new AppError('Bed not found', 404, 'BED_NOT_FOUND'); if (status === 'OCCUPIED' || status === 'RESERVED') throw new AppError('Occupied and reserved statuses are controlled by the admission workflow', 409, 'BED_STATUS_MANAGED_BY_ADMISSIONS'); if (previous.status === 'OCCUPIED' || previous.status === 'RESERVED') throw new AppError('An occupied or reserved bed cannot be changed from master configuration', 409, 'BED_OPERATIONAL_STATE'); if (previous.status === 'INACTIVE' && status !== 'INACTIVE') { const ward = await this.repository.getWard(previous.ward_id, branchId); if (!ward || ward.status !== 'ACTIVE') throw new AppError('A bed cannot be activated under an inactive ward', 409, 'WARD_INACTIVE'); if (ward.capacity) { const configuredBeds = await this.repository.countBedsForWard(previous.ward_id, branchId); if (configuredBeds >= ward.capacity) throw new AppError('Ward capacity has been reached', 409, 'WARD_CAPACITY_REACHED'); } } const bed = await this.repository.updateBedStatus(id, branchId, status, actor); if (!bed) throw new AppError('Bed not found', 404, 'BED_NOT_FOUND'); await this.repository.audit('admissions.bed.status_changed', actor, metadata, { bedId: id, branchId, oldValue: previous.status, newValue: status }); return bed; }
  async summary(branchId: string, actor: string) { await this.authorize(actor, branchId); return this.repository.summary(branchId); }
}
