import type { FastifyInstance, FastifyRequest } from 'fastify';
import { requirePermission } from '../../middleware/require-permission.js';
import { ok } from '../../shared/http/response.js';
import type { ServiceRegistry } from '../../shared/types/service-registry.js';
import { bedBodySchema, bedListSchema, bedStatusSchema, idParamsSchema, updateBedBodySchema, wardBodySchema, wardListSchema, wardStatusSchema } from './admissions-configuration.schemas.js';

const metadata = (request: FastifyRequest) => ({ ipAddress: request.ip, userAgent: request.headers['user-agent'] });
const parse = <T>(schema: { parse(value: unknown): T }, value: unknown) => schema.parse(value);
export const registerAdmissionsConfigurationRoutes = async (app: FastifyInstance, services: ServiceRegistry) => {
  app.get('/api/admissions/wards', { preHandler: requirePermission(services, 'Admissions', 'Wards', 'View') }, async (request) => ok(await services.admissionsConfiguration.listWards(parse(wardListSchema, request.query), request.user!.id)));
  app.get('/api/admissions/wards/:id', { preHandler: requirePermission(services, 'Admissions', 'Wards', 'View') }, async (request) => { const params = parse(idParamsSchema, request.params); const query = parse(wardListSchema.pick({ branch_id: true }), request.query); return ok(await services.admissionsConfiguration.getWard(params.id, query.branch_id, request.user!.id)); });
  app.post('/api/admissions/wards', { preHandler: requirePermission(services, 'Admissions', 'Wards', 'Create') }, async (request, reply) => reply.status(201).send(ok(await services.admissionsConfiguration.createWard(parse(wardBodySchema, request.body), request.user!.id, metadata(request)))));
  app.patch('/api/admissions/wards/:id', { preHandler: requirePermission(services, 'Admissions', 'Wards', 'Edit') }, async (request) => { const params = parse(idParamsSchema, request.params); return ok(await services.admissionsConfiguration.updateWard(params.id, parse(wardBodySchema, request.body), request.user!.id, metadata(request))); });
  app.patch('/api/admissions/wards/:id/status', { preHandler: requirePermission(services, 'Admissions', 'Wards', 'ChangeStatus') }, async (request) => { const params = parse(idParamsSchema, request.params); const body = parse(wardStatusSchema, request.body); return ok(await services.admissionsConfiguration.updateWardStatus(params.id, body.branch_id, body.status, request.user!.id, metadata(request))); });
  app.get('/api/admissions/beds/summary', { preHandler: requirePermission(services, 'Admissions', 'Beds', 'View') }, async (request) => { const query = parse(wardListSchema.pick({ branch_id: true }), request.query); return ok(await services.admissionsConfiguration.summary(query.branch_id, request.user!.id)); });
  app.get('/api/admissions/beds', { preHandler: requirePermission(services, 'Admissions', 'Beds', 'View') }, async (request) => ok(await services.admissionsConfiguration.listBeds(parse(bedListSchema, request.query), request.user!.id)));
  app.get('/api/admissions/beds/:id', { preHandler: requirePermission(services, 'Admissions', 'Beds', 'View') }, async (request) => { const params = parse(idParamsSchema, request.params); const query = parse(wardListSchema.pick({ branch_id: true }), request.query); return ok(await services.admissionsConfiguration.getBed(params.id, query.branch_id, request.user!.id)); });
  app.post('/api/admissions/beds', { preHandler: requirePermission(services, 'Admissions', 'Beds', 'Create') }, async (request, reply) => reply.status(201).send(ok(await services.admissionsConfiguration.createBed(parse(bedBodySchema, request.body), request.user!.id, metadata(request)))));
  app.patch('/api/admissions/beds/:id', { preHandler: requirePermission(services, 'Admissions', 'Beds', 'Edit') }, async (request) => { const params = parse(idParamsSchema, request.params); const body = parse(updateBedBodySchema, request.body); return ok(await services.admissionsConfiguration.updateBed(params.id, body, request.user!.id, metadata(request))); });
  app.patch('/api/admissions/beds/:id/status', { preHandler: requirePermission(services, 'Admissions', 'Beds', 'ChangeStatus') }, async (request) => { const params = parse(idParamsSchema, request.params); const body = parse(bedStatusSchema, request.body); return ok(await services.admissionsConfiguration.updateBedStatus(params.id, body.branch_id, body.status, request.user!.id, metadata(request))); });
};
