import { AppError } from '../../shared/errors/app-error.js';
import type { InpatientAdmissionRepository } from './inpatient-admission.repository.js';
import type { AdmissionRequestMetadata, CreateInpatientAdmissionDTO, InpatientAdmissionListQuery } from './inpatient-admission.types.js';
export class InpatientAdmissionService {
  constructor(private readonly repository: InpatientAdmissionRepository) {}
  async list(query: InpatientAdmissionListQuery, actor: string) { if (!await this.repository.hasBranchAccess(actor, query.branch_id)) throw new AppError('Branch access denied', 403, 'BRANCH_ACCESS_DENIED'); return this.repository.list(query); }
  async get(id: string, branchId: string, actor: string) { if (!await this.repository.hasBranchAccess(actor, branchId)) throw new AppError('Branch access denied', 403, 'BRANCH_ACCESS_DENIED'); const item = await this.repository.getById(id, branchId); if (!item) throw new AppError('Inpatient admission not found', 404, 'ADMISSION_NOT_FOUND'); return item; }
  async create(data: CreateInpatientAdmissionDTO, actor: string, metadata: AdmissionRequestMetadata) { if (!await this.repository.hasBranchAccess(actor, data.branch_id)) throw new AppError('Branch access denied', 403, 'BRANCH_ACCESS_DENIED'); const session = await this.repository.session(); try { let result; await session.withTransaction(async () => { const refs = await this.repository.references(data, session); if (!refs.patient) throw new AppError('Active patient not found', 404, 'PATIENT_NOT_FOUND'); if (!refs.doctor) throw new AppError('Active doctor is not available in this branch', 404, 'DOCTOR_NOT_FOUND'); if (!refs.department) throw new AppError('Active department is not available in this branch', 404, 'DEPARTMENT_NOT_FOUND'); if (!refs.ward) throw new AppError('Active ward not found in this branch', 404, 'WARD_NOT_FOUND'); const bed = await this.repository.occupyBed(data, actor, session); if (!bed) throw new AppError('Selected bed is not available; refresh and choose another bed', 409, 'BED_NOT_AVAILABLE'); result = await this.repository.create(data, { patientNumber: refs.patient.patientNumber, patientName: [refs.patient.firstName, refs.patient.middleName, refs.patient.lastName].filter(Boolean).join(' '), doctorName: refs.doctor.displayName, departmentName: refs.department.name }, actor, session); await this.repository.audit('admissions.inpatient.created', actor, metadata, { admissionId: result.id, patientId: data.patient_id, branchId: data.branch_id, wardId: data.ward_id, bedId: data.bed_id }, session); }); if (!result) throw new AppError('Admission could not be created', 500, 'ADMISSION_CREATE_FAILED'); return result; } finally { await session.endSession(); } }
}
