import mongoose, { Types, type ClientSession } from 'mongoose';
import { AuditLogModel } from '../auth/auth.model.js';
import { BranchModel } from '../branches/branch.model.js';
import { DepartmentModel } from '../departments/department.model.js';
import { DoctorModel } from '../doctors/doctor.model.js';
import { PatientModel } from '../patients/patient.model.js';
import { RoleModel } from '../roles/role.model.js';
import { UserModel } from '../users/user.model.js';
import { BedModel, WardModel } from '../admissions-configuration/admissions-configuration.model.js';
import { InpatientAdmissionModel, type InpatientAdmissionFields } from './inpatient-admission.model.js';
import type { AdmissionRequestMetadata, CreateInpatientAdmissionDTO, InpatientAdmission, InpatientAdmissionListQuery } from './inpatient-admission.types.js';
const oid = (value: string) => new Types.ObjectId(value);
const meta = (total: number, page: number, limit: number) => ({ total, page, limit, totalPages: Math.ceil(total / limit) || 1 });
const toDto = (item: InpatientAdmissionFields & { _id: Types.ObjectId; wardName?: string; bedNumber?: string }): InpatientAdmission => ({ id: item._id.toString(), admission_number: item.admissionNumber, patient_id: item.patientId.toString(), patient_number: item.patientNumber, patient_name: item.patientName, branch_id: item.branchId.toString(), ward_id: item.wardId.toString(), ward_name: item.wardName ?? '', bed_id: item.bedId.toString(), bed_number: item.bedNumber ?? '', admitting_doctor_id: item.admittingDoctorId.toString(), admitting_doctor_name: item.admittingDoctorName, department_id: item.departmentId.toString(), department_name: item.departmentName, admission_date: item.admissionDate, admission_type: item.admissionType, reason: item.reason, notes: item.notes ?? null, status: item.status, created_at: item.createdAt, updated_at: item.updatedAt });
export class InpatientAdmissionRepository {
  async hasBranchAccess(userId: string, branchId: string) { const [user, branch] = await Promise.all([UserModel.findOne({ _id: userId, status: 'active', deletedAt: null }).select('branchIds roleIds').lean(), BranchModel.exists({ _id: branchId, status: 'ACTIVE', deletedAt: null })]); if (!user || !branch) return false; if ((user.branchIds ?? []).some((id) => id.toString() === branchId)) return true; return Boolean(await RoleModel.exists({ _id: { $in: user.roleIds ?? [] }, code: 'SUPER_ADMIN', status: 'active', deletedAt: null })); }
  async references(data: CreateInpatientAdmissionDTO, session: ClientSession) { const [patient, doctor, department, ward] = await Promise.all([PatientModel.findOne({ _id: oid(data.patient_id), status: 'ACTIVE', deletedAt: null }).lean(), DoctorModel.findOne({ _id: oid(data.admitting_doctor_id), branchId: oid(data.branch_id), status: 'ACTIVE', deletedAt: null }).lean(), DepartmentModel.findOne({ _id: oid(data.department_id), branchIds: oid(data.branch_id), status: 'ACTIVE', deletedAt: null }).lean(), WardModel.findOne({ _id: oid(data.ward_id), branchId: oid(data.branch_id), status: 'ACTIVE' }).session(session).lean()]); return { patient, doctor, department, ward }; }
  async occupyBed(data: CreateInpatientAdmissionDTO, userId: string, session: ClientSession) { return BedModel.findOneAndUpdate({ _id: oid(data.bed_id), branchId: oid(data.branch_id), wardId: oid(data.ward_id), status: 'AVAILABLE' }, { $set: { status: 'OCCUPIED', updatedBy: oid(userId) } }, { returnDocument: 'after', session }).lean(); }
  async create(data: CreateInpatientAdmissionDTO, refs: { patientNumber: string; patientName: string; doctorName: string; departmentName: string }, userId: string, session: ClientSession) { const created = await InpatientAdmissionModel.create([{ admissionNumber: `ADM-${Date.now()}-${Math.floor(Math.random() * 1000)}`, patientId: oid(data.patient_id), patientNumber: refs.patientNumber, patientName: refs.patientName, branchId: oid(data.branch_id), wardId: oid(data.ward_id), bedId: oid(data.bed_id), admittingDoctorId: oid(data.admitting_doctor_id), admittingDoctorName: refs.doctorName, departmentId: oid(data.department_id), departmentName: refs.departmentName, admissionDate: new Date(data.admission_date), admissionType: data.admission_type, reason: data.reason, notes: data.notes ?? null, status: 'ADMITTED', createdBy: oid(userId), updatedBy: oid(userId) }], { session }); const first = created[0]; if (!first) throw new Error('Admission create returned no record'); return toDto(first.toObject() as InpatientAdmissionFields & { _id: Types.ObjectId }); }
  async list(query: InpatientAdmissionListQuery) { const page = query.page ?? 1; const limit = query.limit ?? 20; const filter: Record<string, unknown> = { branchId: oid(query.branch_id) }; if (query.status) filter.status = query.status; const [items, total] = await Promise.all([InpatientAdmissionModel.aggregate<InpatientAdmissionFields & { _id: Types.ObjectId; wardName?: string; bedNumber?: string }>([{ $match: filter }, { $lookup: { from: 'hmswards', localField: 'wardId', foreignField: '_id', as: 'ward' } }, { $lookup: { from: 'hmsbeds', localField: 'bedId', foreignField: '_id', as: 'bed' } }, { $set: { wardName: { $ifNull: [{ $arrayElemAt: ['$ward.name', 0] }, ''] }, bedNumber: { $ifNull: [{ $arrayElemAt: ['$bed.bedNumber', 0] }, ''] } } }, { $sort: { admissionDate: -1, _id: -1 } }, { $skip: (page - 1) * limit }, { $limit: limit }]), InpatientAdmissionModel.countDocuments(filter)]); return { data: items.map(toDto), meta: meta(total, page, limit) }; }
  async getById(id: string, branchId: string) { const item = await InpatientAdmissionModel.findOne({ _id: oid(id), branchId: oid(branchId) }).lean(); return item ? toDto(item as InpatientAdmissionFields & { _id: Types.ObjectId }) : null; }
  async audit(eventType: string, actor: string, metadata: AdmissionRequestMetadata, details: Record<string, unknown>, session: ClientSession) { await AuditLogModel.create([{ eventType, actorUserId: actor, ipAddress: metadata.ipAddress, userAgent: metadata.userAgent, metadataJson: details }], { session }); }
  async session() { return mongoose.startSession(); }
}
