export { OpdConsultationTab, type ConsultationForm } from './OpdConsultationTab';
export { OpdPrescriptionTab, type PrescriptionForm } from './OpdPrescriptionTab';
export { OpdVitalsModal, type VitalsForm } from './OpdVitalsModal';
export { OpdLabOrdersTab } from './OpdLabOrdersTab';
export { OpdImagingOrdersTab } from './OpdImagingOrdersTab';
export { OpdReferralTab } from './OpdReferralTab';
export { OpdConsultationSection } from './OpdConsultationSection';
export { OpdDiagnosisTab } from './OpdDiagnosisTab';
export { OpdPrescriptionSection } from './OpdPrescriptionSection';
export { OpdLabSection } from './OpdLabSection';
export { OpdImagingSection } from './OpdImagingSection';
export { OpdReferralSection } from './OpdReferralSection';
export { OpdFollowUpTab } from './OpdFollowUpTab';
export { OpdNotesTab } from './OpdNotesTab';
export { OpdDocumentsTab } from './OpdDocumentsTab';
export { OpdSummaryPanel } from './OpdSummaryPanel';
export { OpdClinicalVitalsModal } from './OpdClinicalVitalsModal';
export { VitalsCaptureModal } from './VitalsCaptureModal';
export { OpdDentalExaminationTab } from './dental/OpdDentalExaminationTab';
export { OdontogramChart } from './dental/OdontogramChart';
export { ToothExaminationPanel } from './dental/ToothExaminationPanel';
export { ToothSurfaceSelector } from './dental/ToothSurfaceSelector';
export { DentalHistorySection } from './dental/DentalHistorySection';
export { DentalSoftTissueSection } from './dental/DentalSoftTissueSection';
export { DentalTreatmentPlanSection } from './dental/DentalTreatmentPlanSection';
