import { zodResolver } from '@hookform/resolvers/zod';
import { useEffect, useMemo, useState } from 'react';
import { useForm } from 'react-hook-form';
import { toast } from 'sonner';
import { z } from 'zod';
import type { ProcedureBooking, ProcedureRecommendation } from '../api/surgery';
import { Modal } from '../components/ui/Modal';
import { StatusBadge } from '../components/ui/StatusBadge';
import { useSurgeryWorkspaceFeature } from '../hooks/surgery/useSurgeryWorkspaceFeature';

const recommendationSchema = z.object({ patient_id: z.string().min(1, 'Select a patient'), department_id: z.string().min(1, 'Select a department'), recommending_doctor_id: z.string().min(1, 'Select a doctor'), service_id: z.string().min(1, 'Select a procedure'), encounter_id: z.string().regex(/^[a-f\d]{24}$/i, 'Enter a valid OPD visit ID'), clinical_reason: z.string().trim().min(3, 'Clinical reason is required').max(1000), notes: z.string().max(2000) });
const bookingSchema = z.object({ doctor_id: z.string().min(1, 'Select a doctor'), scheduled_start: z.string().min(1, 'Select date and time'), hold_id: z.string(), consent_document_id: z.string(), deposit_invoice_id: z.string(), notes: z.string().max(2000) });
const actionSchema = z.object({ scheduled_start: z.string(), doctor_id: z.string(), hold_id: z.string(), consent_document_id: z.string(), deposit_invoice_id: z.string(), reason: z.string() });
type RecommendationValues = z.infer<typeof recommendationSchema>; type BookingValues = z.infer<typeof bookingSchema>; type ActionValues = z.infer<typeof actionSchema>;
type ActionMode = 'confirm' | 'reschedule' | 'cancel-booking' | 'cancel-recommendation' | 'complete' | null;
const statusTone = (status: string) => status === 'BOOKED' || status === 'COMPLETED' ? 'green' : status === 'CANCELLED' ? 'red' : status === 'PENDING_CONFIRMATION' ? 'orange' : 'blue';
const displayDate = (value: string) => new Date(value).toLocaleString([], { dateStyle: 'medium', timeStyle: 'short' });
const localDateTime = (value: string) => { const date = new Date(value); const offset = date.getTimezoneOffset() * 60000; return new Date(date.getTime() - offset).toISOString().slice(0, 16); };

export function SurgeryWorkspacePage() {
  const feature = useSurgeryWorkspaceFeature(); const { state, actions, mutations } = feature;
  const [recommendationOpen, setRecommendationOpen] = useState(false); const [bookingFor, setBookingFor] = useState<ProcedureRecommendation | null>(null); const [selected, setSelected] = useState<ProcedureBooking | null>(null); const [actionMode, setActionMode] = useState<ActionMode>(null);
  const recommendationForm = useForm<RecommendationValues>({ resolver: zodResolver(recommendationSchema), defaultValues: { patient_id: '', department_id: '', recommending_doctor_id: '', service_id: '', encounter_id: '', clinical_reason: '', notes: '' } });
  const bookingForm = useForm<BookingValues>({ resolver: zodResolver(bookingSchema), defaultValues: { doctor_id: '', scheduled_start: '', hold_id: '', consent_document_id: '', deposit_invoice_id: '', notes: '' } });
  const actionForm = useForm<ActionValues>({ resolver: zodResolver(actionSchema), defaultValues: { scheduled_start: '', doctor_id: '', hold_id: '', consent_document_id: '', deposit_invoice_id: '', reason: '' } });
  const departmentId = bookingFor?.department_id ?? ''; const eligibleDoctors = useMemo(() => state.doctors.filter((item) => !departmentId || item.department_id === departmentId), [departmentId, state.doctors]);
  const watchedStart = bookingForm.watch('scheduled_start');
  useEffect(() => { if (bookingFor && watchedStart) actions.setAvailability({ department_id: bookingFor.department_id, service_id: bookingFor.service_id, scheduled_start: new Date(watchedStart).toISOString() }); }, [actions, bookingFor, watchedStart]);
  useEffect(() => { if (selected) actionForm.reset({ scheduled_start: localDateTime(selected.scheduled_start), doctor_id: selected.doctor_id, hold_id: selected.hold_id ?? '', consent_document_id: selected.consent_document_id ?? '', deposit_invoice_id: selected.deposit_invoice_id ?? '', reason: '' }); }, [actionForm, selected]);
  const procedure = bookingFor ? state.services.find((item) => item.id === bookingFor.service_id) : selected ? state.services.find((item) => item.id === selected.service_id) : undefined;

  const createRecommendation = recommendationForm.handleSubmit(async (values) => { try { await mutations.createRecommendation.mutateAsync({ ...values, branch_id: state.branchId, encounter_type: 'OPD_VISIT', notes: values.notes || null }); toast.success('Procedure recommendation created.'); setRecommendationOpen(false); recommendationForm.reset(); } catch (error) { toast.error(error instanceof Error ? error.message : 'Unable to create recommendation.'); } });
  const createBooking = bookingForm.handleSubmit(async (values) => { if (!bookingFor) return; try { const booking = await mutations.createBooking.mutateAsync({ recommendation_id: bookingFor.id, branch_id: state.branchId, doctor_id: values.doctor_id, scheduled_start: new Date(values.scheduled_start).toISOString(), hold_id: values.hold_id || null, consent_document_id: values.consent_document_id || null, deposit_invoice_id: values.deposit_invoice_id || null, notes: values.notes || null }); toast.success('Booking created and awaiting prerequisite confirmation.'); setBookingFor(null); setSelected(booking); bookingForm.reset(); actions.setTab('bookings'); } catch (error) { toast.error(error instanceof Error ? error.message : 'Unable to create booking.'); } });
  const executeAction = actionForm.handleSubmit(async (values) => { try { if (actionMode === 'cancel-recommendation' && bookingFor) await mutations.cancelRecommendation.mutateAsync({ id: bookingFor.id, reason: values.reason }); if (selected && actionMode === 'confirm') await mutations.confirmBooking.mutateAsync({ id: selected.id, body: { hold_id: values.hold_id || null, consent_document_id: values.consent_document_id || null, deposit_invoice_id: values.deposit_invoice_id || null } }); if (selected && actionMode === 'reschedule') { if (values.reason.trim().length < 3) throw new Error('Reschedule reason is required.'); await mutations.rescheduleBooking.mutateAsync({ id: selected.id, body: { scheduled_start: new Date(values.scheduled_start).toISOString(), doctor_id: values.doctor_id, hold_id: values.hold_id || null, consent_document_id: values.consent_document_id || null, deposit_invoice_id: values.deposit_invoice_id || null, reason: values.reason } }); } if (selected && actionMode === 'cancel-booking') { if (values.reason.trim().length < 3) throw new Error('Cancellation reason is required.'); await mutations.cancelBooking.mutateAsync({ id: selected.id, reason: values.reason }); } if (selected && actionMode === 'complete') await mutations.completeBooking.mutateAsync(selected.id); toast.success(actionMode === 'reschedule' ? 'Procedure rescheduled.' : actionMode === 'confirm' ? 'Procedure booking confirmed.' : actionMode === 'complete' ? 'Procedure marked completed.' : 'Cancellation completed.'); setActionMode(null); setBookingFor(null); setSelected(null); } catch (error) { toast.error(error instanceof Error ? error.message : 'Action could not be completed.'); } });

  if (!state.branchId && state.branches.length === 0) return <div className="admin-dashboard-state"><i className="ph ph-buildings"/><strong>No authorized branch</strong><span>Assign this user to a branch before managing procedure bookings.</span></div>;
  return <div className="page-shell">
    <div className="page-heading"><div><h1>Surgery &amp; Procedures</h1><p>Coordinate recommendations, prerequisites and procedure schedules</p></div><div className="page-actions"><select aria-label="Branch" value={state.branchId} onChange={(event) => actions.setBranchId(event.target.value)}>{state.branches.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select><button className="btn-primary" onClick={() => setRecommendationOpen(true)}><i className="ph ph-plus"/> New Recommendation</button></div></div>
    <section className="kpi-grid"><div className="kpi-card"><span className="kpi-title">Active recommendations</span><strong className="kpi-value">{state.recommendations.filter((item) => item.status === 'ACTIVE').length}</strong></div><div className="kpi-card"><span className="kpi-title">Pending confirmation</span><strong className="kpi-value">{state.bookings.filter((item) => item.status === 'PENDING_CONFIRMATION').length}</strong></div><div className="kpi-card"><span className="kpi-title">Booked</span><strong className="kpi-value">{state.bookings.filter((item) => item.status === 'BOOKED').length}</strong></div><div className="kpi-card"><span className="kpi-title">Completed</span><strong className="kpi-value">{state.bookings.filter((item) => item.status === 'COMPLETED').length}</strong></div></section>
    <div className="filters-toolbar"><div className="segmented-control"><button className={state.tab === 'recommendations' ? 'active' : ''} onClick={() => actions.setTab('recommendations')}>Recommendations</button><button className={state.tab === 'bookings' ? 'active' : ''} onClick={() => actions.setTab('bookings')}>Bookings</button><button className={state.tab === 'schedule' ? 'active' : ''} onClick={() => actions.setTab('schedule')}>Schedule</button></div><label><span>Search</span><input placeholder="Number, MRN, patient or procedure" value={state.searchText} onChange={(event) => actions.setSearchText(event.target.value)} /></label><label><span>Status</span><select value={state.status} onChange={(event) => actions.setStatus(event.target.value)}><option value="">All statuses</option>{state.tab === 'recommendations' ? <><option value="ACTIVE">Active</option><option value="BOOKED">Booked</option><option value="CANCELLED">Cancelled</option></> : <><option value="PENDING_CONFIRMATION">Pending confirmation</option><option value="BOOKED">Booked</option><option value="COMPLETED">Completed</option><option value="CANCELLED">Cancelled</option></>}</select></label>{state.tab === 'schedule' ? <label><span>Date</span><input type="date" value={state.date} onChange={(event) => actions.setDate(event.target.value)} /></label> : null}</div>
    {state.tab === 'recommendations' ? <div className="table-scroll"><table className="data-table"><thead><tr><th>Recommendation</th><th>Patient</th><th>Procedure</th><th>Doctor / Department</th><th>Clinical reason</th><th>Status</th><th>Actions</th></tr></thead><tbody>{state.recommendationsQuery.isLoading ? <StateRow columns={7} text="Loading recommendations..."/> : state.recommendationsQuery.isError ? <StateRow columns={7} text="Unable to load recommendations."/> : state.recommendations.length === 0 ? <StateRow columns={7} text="No live procedure recommendations found."/> : state.recommendations.map((item) => <tr key={item.id}><td><strong>{item.recommendation_number}</strong><br/><small>{new Date(item.created_at).toLocaleDateString()}</small></td><td>{item.patient_name}<br/><small>{item.patient_number}</small></td><td>{item.service_name}</td><td>{item.recommending_doctor_name}<br/><small>{item.department_name}</small></td><td>{item.clinical_reason}</td><td><StatusBadge tone={statusTone(item.status)}>{item.status}</StatusBadge></td><td><div className="table-actions">{item.status === 'ACTIVE' ? <><button className="btn-primary compact" onClick={() => { setBookingFor(item); bookingForm.reset(); }}>Book</button><button className="btn-danger compact" onClick={() => { setBookingFor(item); setActionMode('cancel-recommendation'); }}>Cancel</button></> : item.booking_id ? <button className="btn-secondary compact" onClick={() => actions.setTab('bookings')}>View booking</button> : null}</div></td></tr>)}</tbody></table></div> : null}
    {state.tab === 'bookings' ? <div className="table-scroll"><table className="data-table"><thead><tr><th>Booking</th><th>Patient</th><th>Procedure</th><th>Schedule</th><th>Doctor</th><th>Prerequisites</th><th>Status</th><th>Actions</th></tr></thead><tbody>{state.bookingsQuery.isLoading ? <StateRow columns={8} text="Loading procedure bookings..."/> : state.bookingsQuery.isError ? <StateRow columns={8} text="Unable to load procedure bookings."/> : state.bookings.length === 0 ? <StateRow columns={8} text="No live procedure bookings found."/> : state.bookings.map((item) => <tr key={item.id}><td><strong>{item.booking_number}</strong></td><td>{item.patient_name}<br/><small>{item.patient_number}</small></td><td>{item.service_name}<br/><small>{item.duration_minutes} min</small></td><td>{displayDate(item.scheduled_start)}</td><td>{item.doctor_name}</td><td><RequirementFlags booking={item} service={state.services.find((service) => service.id === item.service_id)} /></td><td><StatusBadge tone={statusTone(item.status)}>{item.status.replaceAll('_', ' ')}</StatusBadge></td><td><button className="btn-secondary compact" onClick={() => setSelected(item)}>Review</button></td></tr>)}</tbody></table></div> : null}
    {state.tab === 'schedule' ? <section className="content-card"><div className="section-heading"><div><h2>Procedure Schedule</h2><p>All doctors and active procedure bookings for {new Date(`${state.date}T00:00:00`).toLocaleDateString()}</p></div></div>{state.bookingsQuery.isLoading ? <div className="empty-state">Loading schedule...</div> : state.bookingsQuery.isError ? <div className="error-state">Unable to load the procedure schedule.</div> : state.scheduleRows.length === 0 ? <div className="empty-state">No procedures are scheduled for this date.</div> : <div className="schedule-timeline">{state.scheduleRows.map((item) => <button type="button" className="schedule-event" key={item.id} onClick={() => setSelected(item)}><span>{new Date(item.scheduled_start).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })}</span><strong>{item.patient_name} · {item.service_name}</strong><small>{item.doctor_name} · {item.department_name}</small><StatusBadge tone={statusTone(item.status)}>{item.status.replaceAll('_', ' ')}</StatusBadge></button>)}</div>}</section> : null}

    <Modal open={recommendationOpen} onClose={() => setRecommendationOpen(false)} title="New Procedure Recommendation"><form className="form-grid" onSubmit={createRecommendation}><label className="form-grid__full">Search patient<input value={state.patientSearch} onChange={(event) => actions.setPatientSearch(event.target.value)} placeholder="MRN, patient name or phone" /></label><label className="form-grid__full">Patient<select {...recommendationForm.register('patient_id')}><option value="">Select patient</option>{state.patients.map((item) => <option value={item.id} key={item.id}>{item.patient_number} · {item.first_name} {item.last_name}</option>)}</select><FieldError text={recommendationForm.formState.errors.patient_id?.message}/></label><label>Department<select {...recommendationForm.register('department_id')}><option value="">Select department</option>{state.departments.map((item) => <option value={item.id} key={item.id}>{item.name}</option>)}</select></label><label>Recommending doctor<select {...recommendationForm.register('recommending_doctor_id')}><option value="">Select doctor</option>{state.doctors.filter((item) => !recommendationForm.watch('department_id') || item.department_id === recommendationForm.watch('department_id')).map((item) => <option value={item.id} key={item.id}>{item.display_name}</option>)}</select></label><label>Procedure<select {...recommendationForm.register('service_id')}><option value="">Select procedure</option>{state.services.filter((item) => !recommendationForm.watch('department_id') || item.department_id === recommendationForm.watch('department_id')).map((item) => <option value={item.id} key={item.id}>{item.name}</option>)}</select></label><label>OPD visit ID<input {...recommendationForm.register('encounter_id')} /><FieldError text={recommendationForm.formState.errors.encounter_id?.message}/></label><label className="form-grid__full">Clinical reason<textarea {...recommendationForm.register('clinical_reason')} /><FieldError text={recommendationForm.formState.errors.clinical_reason?.message}/></label><label className="form-grid__full">Notes<textarea {...recommendationForm.register('notes')} /></label><div className="form-grid__full page-actions"><button type="button" className="btn-secondary" onClick={() => setRecommendationOpen(false)}>Close</button><button className="btn-primary" disabled={mutations.createRecommendation.isPending || !state.branchId}>Create Recommendation</button></div></form></Modal>
    <Modal open={Boolean(bookingFor && !actionMode)} onClose={() => setBookingFor(null)} title="Book Recommended Procedure"><form className="form-grid" onSubmit={createBooking}><div className="form-grid__full booking-steps"><span className="active">1 Recommendation</span><span className="active">2 Schedule</span><span>3 Confirm prerequisites</span></div><div className="form-grid__full details-list"><div className="details-list-item"><span>Patient</span><strong>{bookingFor?.patient_name}</strong></div><div className="details-list-item"><span>Procedure</span><strong>{bookingFor?.service_name}</strong></div><div className="details-list-item"><span>Configured duration</span><strong>{procedure?.default_duration_minutes ?? '-'} min</strong></div></div><label>Doctor<select {...bookingForm.register('doctor_id')}><option value="">Select doctor</option>{eligibleDoctors.map((item) => <option value={item.id} key={item.id}>{item.display_name}</option>)}</select></label><label>Start date and time<input type="datetime-local" {...bookingForm.register('scheduled_start')} /></label>{watchedStart ? <div className="form-grid__full prerequisite-panel"><strong>Available doctors for this interval</strong><p>{state.alternativesLoading ? 'Checking availability...' : state.alternatives.length ? state.alternatives.map((item) => item.doctor_name).join(', ') : 'No alternative doctors are available.'}</p></div> : null}<label>Bed hold ID {procedure?.requires_bed ? '(required before confirmation)' : '(not required)'}<input {...bookingForm.register('hold_id')} /></label><label>Consent document ID {procedure?.requires_consent ? '(required before confirmation)' : '(not required)'}<input {...bookingForm.register('consent_document_id')} /></label><label>Deposit invoice ID {procedure?.requires_advance_deposit ? `(minimum ${procedure.minimum_advance_deposit_amount ?? 0})` : '(not required)'}<input {...bookingForm.register('deposit_invoice_id')} /></label><label className="form-grid__full">Notes<textarea {...bookingForm.register('notes')} /></label><div className="form-grid__full page-actions"><button type="button" className="btn-secondary" onClick={() => setBookingFor(null)}>Close</button><button className="btn-primary" disabled={mutations.createBooking.isPending}>Create Pending Booking</button></div></form></Modal>
    <Modal open={Boolean(selected && !actionMode)} onClose={() => setSelected(null)} title="Procedure Booking Detail">{selected ? <div className="stack"><div className="details-list"><div className="details-list-item"><span>Booking</span><strong>{selected.booking_number}</strong></div><div className="details-list-item"><span>Patient</span><strong>{selected.patient_name} · {selected.patient_number}</strong></div><div className="details-list-item"><span>Procedure</span><strong>{selected.service_name}</strong></div><div className="details-list-item"><span>Schedule</span><strong>{displayDate(selected.scheduled_start)}</strong></div><div className="details-list-item"><span>Doctor</span><strong>{selected.doctor_name}</strong></div></div><div className="prerequisite-panel"><strong>Confirmation blockers</strong><RequirementFlags booking={selected} service={procedure}/></div>{selected.schedule_history.length ? <div><h3>Reschedule history</h3>{selected.schedule_history.map((row) => <div className="details-list-item" key={row.changed_at}><span>{displayDate(row.previous_start)} → {displayDate(row.new_start)}</span><strong>{row.reason}</strong></div>)}</div> : null}<div className="page-actions">{selected.status === 'PENDING_CONFIRMATION' ? <button className="btn-primary" onClick={() => setActionMode('confirm')}>Confirm Booking</button> : null}{selected.status === 'BOOKED' ? <><button className="btn-secondary" onClick={() => setActionMode('reschedule')}>Reschedule</button><button className="btn-primary" onClick={() => setActionMode('complete')}>Complete</button></> : null}{['PENDING_CONFIRMATION', 'BOOKED'].includes(selected.status) ? <button className="btn-danger" onClick={() => setActionMode('cancel-booking')}>Cancel</button> : null}</div></div> : null}</Modal>
    <Modal open={Boolean(actionMode)} onClose={() => setActionMode(null)} title={actionMode === 'confirm' ? 'Confirm Procedure Booking' : actionMode === 'reschedule' ? 'Reschedule Procedure' : actionMode === 'complete' ? 'Complete Procedure' : 'Confirm Cancellation'}><form className="form-grid" onSubmit={executeAction}>{actionMode === 'confirm' || actionMode === 'reschedule' ? <><label>Doctor<select {...actionForm.register('doctor_id')} disabled={actionMode === 'confirm'}>{state.doctors.filter((item) => !selected || item.department_id === selected.department_id).map((item) => <option key={item.id} value={item.id}>{item.display_name}</option>)}</select></label><label>Schedule<input type="datetime-local" {...actionForm.register('scheduled_start')} disabled={actionMode === 'confirm'} /></label><label>Bed hold ID<input {...actionForm.register('hold_id')} /></label><label>Signed consent document ID<input {...actionForm.register('consent_document_id')} /></label><label>Paid deposit invoice ID<input {...actionForm.register('deposit_invoice_id')} /></label></> : null}{actionMode === 'reschedule' || actionMode === 'cancel-booking' || actionMode === 'cancel-recommendation' ? <label className="form-grid__full">Reason<textarea {...actionForm.register('reason')} /></label> : null}<div className="form-grid__full page-actions"><button type="button" className="btn-secondary" onClick={() => setActionMode(null)}>Back</button><button className={actionMode?.startsWith('cancel') ? 'btn-danger' : 'btn-primary'}>Confirm</button></div></form></Modal>
  </div>;
}

function StateRow({ columns, text }: { columns: number; text: string }) { return <tr><td colSpan={columns} className="empty-state">{text}</td></tr>; }
function FieldError({ text }: { text?: string }) { return text ? <small className="form-error">{text}</small> : null; }
function RequirementFlags({ booking, service }: { booking: ProcedureBooking; service?: { requires_bed: boolean; requires_consent: boolean; requires_advance_deposit: boolean } }) { const snapshot = booking.prerequisite_snapshot; return <div className="requirement-flags"><span className={!service?.requires_bed || Boolean(booking.hold_id) ? 'met' : 'blocked'}>Bed: {!service?.requires_bed ? 'Not required' : booking.hold_id ? 'Held' : 'Required'}</span><span className={!service?.requires_consent || Boolean(booking.consent_document_id) || Boolean(snapshot) ? 'met' : 'blocked'}>Consent: {!service?.requires_consent ? 'Not required' : booking.consent_document_id || snapshot ? 'Linked' : 'Required'}</span><span className={!service?.requires_advance_deposit || Boolean(booking.deposit_invoice_id) || Boolean(snapshot) ? 'met' : 'blocked'}>Deposit: {!service?.requires_advance_deposit ? 'Not required' : booking.deposit_invoice_id || snapshot ? 'Linked' : 'Required'}</span></div>; }
