import { apiClient } from './client';
export type ProcedureRecommendationStatus = 'ACTIVE' | 'BOOKED' | 'CANCELLED';
export type ProcedureBookingStatus = 'PENDING_CONFIRMATION' | 'BOOKED' | 'COMPLETED' | 'CANCELLED';
export type ProcedureRecommendation = { id: string; recommendation_number: string; patient_id: string; patient_number: string; patient_name: string; branch_id: string; department_id: string; department_name: string; recommending_doctor_id: string; recommending_doctor_name: string; service_id: string; service_name: string; encounter_type: 'OPD_VISIT'; encounter_id: string; clinical_reason: string; notes: string | null; status: ProcedureRecommendationStatus; booking_id: string | null; cancellation_reason: string | null; created_at: string; updated_at: string };
export type ScheduleHistory = { previous_start: string; previous_end: string; new_start: string; new_end: string; previous_doctor_id: string; new_doctor_id: string; reason: string; changed_by: string; changed_at: string };
export type ProcedureBooking = { id: string; booking_number: string; recommendation_id: string; patient_id: string; patient_number: string; patient_name: string; branch_id: string; department_id: string; department_name: string; service_id: string; service_name: string; doctor_id: string; doctor_name: string; scheduled_start: string; scheduled_end: string; duration_minutes: number; status: ProcedureBookingStatus; hold_id: string | null; consent_document_id: string | null; deposit_invoice_id: string | null; prerequisite_snapshot: Record<string, unknown> | null; notes: string | null; schedule_history: ScheduleHistory[]; cancellation_reason: string | null; completed_at: string | null; created_at: string; updated_at: string };
export type SurgeryPage<T> = { data: T[]; meta: { total: number; page: number; limit: number; totalPages: number } };
export type SurgeryListParams = { branch_id: string; status?: string; patient_id?: string; doctor_id?: string; service_id?: string; from?: string; to?: string; search?: string; page?: number; limit?: number };
export type CreateRecommendationPayload = { patient_id: string; branch_id: string; department_id: string; recommending_doctor_id: string; service_id: string; encounter_type: 'OPD_VISIT'; encounter_id: string; clinical_reason: string; notes?: string | null };
export type CreateBookingPayload = { recommendation_id: string; branch_id: string; doctor_id: string; scheduled_start: string; hold_id?: string | null; consent_document_id?: string | null; deposit_invoice_id?: string | null; notes?: string | null };
const query = (params: Record<string, string | number | undefined>) => { const values = new URLSearchParams(); Object.entries(params).forEach(([key, value]) => { if (value !== undefined && value !== '') values.set(key, String(value)); }); return `?${values.toString()}`; };
export const surgeryApi = {
  recommendations: (params: SurgeryListParams) => apiClient.request<SurgeryPage<ProcedureRecommendation>>(`/surgery/recommendations${query(params)}`),
  createRecommendation: (body: CreateRecommendationPayload) => apiClient.request<ProcedureRecommendation>('/surgery/recommendations', { method: 'POST', body }),
  cancelRecommendation: (id: string, branchId: string, reason: string) => apiClient.request<ProcedureRecommendation>(`/surgery/recommendations/${id}/cancel${query({ branch_id: branchId })}`, { method: 'POST', body: { reason } }),
  bookings: (params: SurgeryListParams) => apiClient.request<SurgeryPage<ProcedureBooking>>(`/surgery/bookings${query(params)}`),
  booking: (id: string, branchId: string) => apiClient.request<ProcedureBooking>(`/surgery/bookings/${id}${query({ branch_id: branchId })}`),
  createBooking: (body: CreateBookingPayload) => apiClient.request<ProcedureBooking>('/surgery/bookings', { method: 'POST', body }),
  confirmBooking: (id: string, branchId: string, body: { consent_document_id?: string | null; deposit_invoice_id?: string | null; hold_id?: string | null }) => apiClient.request<ProcedureBooking>(`/surgery/bookings/${id}/confirm${query({ branch_id: branchId })}`, { method: 'POST', body }),
  rescheduleBooking: (id: string, branchId: string, body: { scheduled_start: string; reason: string; doctor_id?: string; hold_id?: string | null; consent_document_id?: string | null; deposit_invoice_id?: string | null }) => apiClient.request<ProcedureBooking>(`/surgery/bookings/${id}/reschedule${query({ branch_id: branchId })}`, { method: 'POST', body }),
  cancelBooking: (id: string, branchId: string, reason: string) => apiClient.request<ProcedureBooking>(`/surgery/bookings/${id}/cancel${query({ branch_id: branchId })}`, { method: 'POST', body: { reason } }),
  completeBooking: (id: string, branchId: string) => apiClient.request<ProcedureBooking>(`/surgery/bookings/${id}/complete${query({ branch_id: branchId })}`, { method: 'POST' }),
  alternatives: (params: { branch_id: string; department_id: string; service_id: string; scheduled_start: string }) => apiClient.request<Array<{ doctor_id: string; doctor_name: string }>>(`/surgery/availability/alternatives${query(params)}`),
};
