import type { checkDatabaseHealth } from '../../database/health.js';
import type { AuthService } from '../../modules/auth/auth.service.js';
import type { PermissionService } from '../../modules/permissions/permission.service.js';
import type { RoleService } from '../../modules/roles/role.service.js';
import type { UserService } from '../../modules/users/user.service.js';
import type { BranchService } from '../../modules/branches/branch.service.js';
import type { DepartmentService } from '../../modules/departments/department.service.js';
import type { AppointmentService } from '../../modules/appointments/appointment.service.js';
import type { DoctorService } from '../../modules/doctors/doctor.service.js';
import type { OpdConsultationService } from '../../modules/opd/opd-consultation.service.js';
import type { OpdClinicalOrderService } from '../../modules/opd/opd-clinical-order.service.js';
import type { OpdPrescriptionService } from '../../modules/opd/opd-prescription.service.js';
import type { OpdFollowUpService } from '../../modules/opd/opd-follow-up.service.js';
import type { OpdReferralService } from '../../modules/opd/opd-referral.service.js';
import type { OpdVitalsService } from '../../modules/opd/opd-vitals.service.js';
import type { OpdVisitService } from '../../modules/opd/opd-visit.service.js';
import type { PatientService } from '../../modules/patients/patient.service.js';
import type { ServiceCatalogueService } from '../../modules/services/service.service.js';
import type { MedicineService } from '../../modules/medicines/medicine.service.js';
import type { PharmacyInventoryService } from '../../modules/pharmacy-inventory/pharmacy-inventory.service.js';
import type { LaboratoryService } from '../../modules/laboratory/laboratory.service.js';
import type { ImagingService } from '../../modules/imaging/imaging.service.js';
import type { BillingService } from '../../modules/billing/billing.service.js';
import type { SettingsService } from '../../modules/settings/settings.service.js';
import type { AdministrationDashboardService } from '../../modules/administration-dashboard/administration-dashboard.service.js';
import type { NotificationService } from '../../modules/notifications/notification.service.js';
import type { PharmacyDispensingService } from '../../modules/pharmacy-dispensing/pharmacy-dispensing.service.js';
import type { AdmissionsConfigurationService } from '../../modules/admissions-configuration/admissions-configuration.service.js';
import type { InpatientAdmissionService } from '../../modules/inpatient-admissions/inpatient-admission.service.js';
import type { SurgeryService } from '../../modules/surgery/surgery.service.js';
import type { EmergencyService } from '../../modules/emergency/emergency.service.js';

export type ServiceRegistry = {
  administrationDashboard: AdministrationDashboardService;
  database: {
    healthCheck: typeof checkDatabaseHealth;
  };
  auth: AuthService;
  users: UserService;
  roles: RoleService;
  permissions: PermissionService;
  branches: BranchService;
  departments: DepartmentService;
  patients: PatientService;
  doctors: DoctorService;
  appointments: AppointmentService;
  opdVisits: OpdVisitService;
  opdVitals: OpdVitalsService;
  opdConsultations: OpdConsultationService;
  opdClinicalOrders: OpdClinicalOrderService;
  opdPrescriptions: OpdPrescriptionService;
  opdFollowUps: OpdFollowUpService;
  opdReferrals: OpdReferralService;
  serviceCatalogue: ServiceCatalogueService;
  medicines: MedicineService;
  pharmacyInventory: PharmacyInventoryService;
  laboratory: LaboratoryService;
  imaging: ImagingService;
  billing: BillingService;
  settings: SettingsService;
  notification: NotificationService;
  pharmacyDispensing: PharmacyDispensingService;
  admissionsConfiguration: AdmissionsConfigurationService;
  inpatientAdmissions: InpatientAdmissionService;
  surgery: SurgeryService;
  emergency: EmergencyService;
};
